// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMailSuppression = `-- name: AddMailSuppression :exec
INSERT INTO mail_suppressions (id, email, reason)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO NOTHING
`

type AddMailSuppressionParams struct {
	ID     pgtype.UUID `json:"id"`
	Email  string      `json:"email"`
	Reason string      `json:"reason"`
}

func (q *Queries) AddMailSuppression(ctx context.Context, arg AddMailSuppressionParams) error {
	_, err := q.db.Exec(ctx, addMailSuppression, arg.ID, arg.Email, arg.Reason)
	return err
}

const incrementReplyTemplateUsage = `-- name: IncrementReplyTemplateUsage :exec
UPDATE reply_templates SET usage_count = usage_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReplyTemplateUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementReplyTemplateUsage, id)
	return err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, actor_id, actor_type, entity, entity_id, action, before, after, ip, user_agent, at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now() AT TIME ZONE 'utc')
`

type InsertAuditLogParams struct {
	ID        pgtype.UUID `json:"id"`
	ActorID   pgtype.UUID `json:"actor_id"`
	ActorType string      `json:"actor_type"`
	Entity    string      `json:"entity"`
	EntityID  pgtype.UUID `json:"entity_id"`
	Action    string      `json:"action"`
	Before    []byte      `json:"before"`
	After     []byte      `json:"after"`
	Ip        *netip.Addr `json:"ip"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.ActorID,
		arg.ActorType,
		arg.Entity,
		arg.EntityID,
		arg.Action,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const isEmailSuppressed = `-- name: IsEmailSuppressed :one
SELECT EXISTS(SELECT 1 FROM mail_suppressions WHERE email = $1 AND deleted_at IS NULL) AS is_suppressed
`

func (q *Queries) IsEmailSuppressed(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailSuppressed, email)
	var is_suppressed bool
	err := row.Scan(&is_suppressed)
	return is_suppressed, err
}

const listActiveAssignmentRules = `-- name: ListActiveAssignmentRules :many
SELECT id, name, is_active, priority_order, trigger, match_conditions, strategy, target_team_id, candidate_agent_ids, active_weekdays, active_from_time, active_to_time, respect_availability, respect_capacity, last_assigned_agent_id, created_at, updated_at, created_by, updated_by, deleted_at FROM assignment_rules 
WHERE is_active = TRUE AND trigger = $1 AND deleted_at IS NULL 
ORDER BY priority_order ASC
`

func (q *Queries) ListActiveAssignmentRules(ctx context.Context, trigger string) ([]AssignmentRules, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentRules, trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssignmentRules
	for rows.Next() {
		var i AssignmentRules
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.PriorityOrder,
			&i.Trigger,
			&i.MatchConditions,
			&i.Strategy,
			&i.TargetTeamID,
			&i.CandidateAgentIds,
			&i.ActiveWeekdays,
			&i.ActiveFromTime,
			&i.ActiveToTime,
			&i.RespectAvailability,
			&i.RespectCapacity,
			&i.LastAssignedAgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAutomationRulesByTrigger = `-- name: ListActiveAutomationRulesByTrigger :many
SELECT id, name, is_active, priority_order, trigger, match_conditions, actions, run_once_per_ticket, schedule_cron, created_at, updated_at, created_by, updated_by, deleted_at FROM automation_rules 
WHERE is_active = TRUE AND trigger = $1 AND deleted_at IS NULL 
ORDER BY priority_order ASC
`

func (q *Queries) ListActiveAutomationRulesByTrigger(ctx context.Context, trigger string) ([]AutomationRules, error) {
	rows, err := q.db.Query(ctx, listActiveAutomationRulesByTrigger, trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationRules
	for rows.Next() {
		var i AutomationRules
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.PriorityOrder,
			&i.Trigger,
			&i.MatchConditions,
			&i.Actions,
			&i.RunOncePerTicket,
			&i.ScheduleCron,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWebhooksForEvent = `-- name: ListActiveWebhooksForEvent :many
SELECT id, name, url, secret, events, is_active, headers, retry_policy, created_at, updated_at, created_by, updated_by, deleted_at FROM webhooks 
WHERE is_active = TRUE AND $1 = ANY(events) AND deleted_at IS NULL
`

func (q *Queries) ListActiveWebhooksForEvent(ctx context.Context, events []string) ([]Webhooks, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksForEvent, events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhooks
	for rows.Next() {
		var i Webhooks
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.Headers,
			&i.RetryPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFieldDefinitions = `-- name: ListAllFieldDefinitions :many
SELECT id, entity, key, label, data_type, options, is_required, is_agent_only, show_in_portal_form, show_in_list, default_value, validation_regex, depends_on, sort_order, created_at, updated_at, created_by, updated_by, deleted_at FROM field_definitions WHERE deleted_at IS NULL ORDER BY entity, sort_order ASC
`

func (q *Queries) ListAllFieldDefinitions(ctx context.Context) ([]FieldDefinitions, error) {
	rows, err := q.db.Query(ctx, listAllFieldDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldDefinitions
	for rows.Next() {
		var i FieldDefinitions
		if err := rows.Scan(
			&i.ID,
			&i.Entity,
			&i.Key,
			&i.Label,
			&i.DataType,
			&i.Options,
			&i.IsRequired,
			&i.IsAgentOnly,
			&i.ShowInPortalForm,
			&i.ShowInList,
			&i.DefaultValue,
			&i.ValidationRegex,
			&i.DependsOn,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentRules = `-- name: ListAssignmentRules :many
SELECT id, name, is_active, priority_order, trigger, match_conditions, strategy, target_team_id, candidate_agent_ids, active_weekdays, active_from_time, active_to_time, respect_availability, respect_capacity, last_assigned_agent_id, created_at, updated_at, created_by, updated_by, deleted_at FROM assignment_rules WHERE deleted_at IS NULL ORDER BY priority_order ASC
`

func (q *Queries) ListAssignmentRules(ctx context.Context) ([]AssignmentRules, error) {
	rows, err := q.db.Query(ctx, listAssignmentRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssignmentRules
	for rows.Next() {
		var i AssignmentRules
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.PriorityOrder,
			&i.Trigger,
			&i.MatchConditions,
			&i.Strategy,
			&i.TargetTeamID,
			&i.CandidateAgentIds,
			&i.ActiveWeekdays,
			&i.ActiveFromTime,
			&i.ActiveToTime,
			&i.RespectAvailability,
			&i.RespectCapacity,
			&i.LastAssignedAgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsKeyset = `-- name: ListAuditLogsKeyset :many
SELECT id, actor_id, actor_type, entity, entity_id, action, before, after, ip, user_agent, at FROM audit_log
WHERE ($1::uuid IS NULL OR entity_id = $1)
  AND ($2::text IS NULL OR entity = $2)
  AND (
    $4::timestamptz IS NULL
    OR (at, id) < ($4, $5::uuid)
  )
ORDER BY at DESC, id DESC
LIMIT $3
`

type ListAuditLogsKeysetParams struct {
	Column1 pgtype.UUID        `json:"column_1"`
	Column2 string             `json:"column_2"`
	Limit   int32              `json:"limit"`
	AfterAt pgtype.Timestamptz `json:"after_at"`
	AfterID pgtype.UUID        `json:"after_id"`
}

func (q *Queries) ListAuditLogsKeyset(ctx context.Context, arg ListAuditLogsKeysetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsKeyset,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.AfterAt,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorType,
			&i.Entity,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.UserAgent,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationRules = `-- name: ListAutomationRules :many
SELECT id, name, is_active, priority_order, trigger, match_conditions, actions, run_once_per_ticket, schedule_cron, created_at, updated_at, created_by, updated_by, deleted_at FROM automation_rules WHERE deleted_at IS NULL ORDER BY priority_order ASC
`

func (q *Queries) ListAutomationRules(ctx context.Context) ([]AutomationRules, error) {
	rows, err := q.db.Query(ctx, listAutomationRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationRules
	for rows.Next() {
		var i AutomationRules
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.PriorityOrder,
			&i.Trigger,
			&i.MatchConditions,
			&i.Actions,
			&i.RunOncePerTicket,
			&i.ScheduleCron,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldDefinitions = `-- name: ListFieldDefinitions :many
SELECT id, entity, key, label, data_type, options, is_required, is_agent_only, show_in_portal_form, show_in_list, default_value, validation_regex, depends_on, sort_order, created_at, updated_at, created_by, updated_by, deleted_at FROM field_definitions WHERE entity = $1 AND deleted_at IS NULL ORDER BY sort_order ASC
`

func (q *Queries) ListFieldDefinitions(ctx context.Context, entity string) ([]FieldDefinitions, error) {
	rows, err := q.db.Query(ctx, listFieldDefinitions, entity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldDefinitions
	for rows.Next() {
		var i FieldDefinitions
		if err := rows.Scan(
			&i.ID,
			&i.Entity,
			&i.Key,
			&i.Label,
			&i.DataType,
			&i.Options,
			&i.IsRequired,
			&i.IsAgentOnly,
			&i.ShowInPortalForm,
			&i.ShowInList,
			&i.DefaultValue,
			&i.ValidationRegex,
			&i.DependsOn,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundMailAccounts = `-- name: ListInboundMailAccounts :many
SELECT id, label, address, direction, is_default_inbound, is_default_outbound, protocol, credentials_encrypted, poll_interval_seconds, last_polled_at, last_uid, default_team_id, default_type_id, strip_quoted_reply, signature_html, created_at, updated_at, created_by, updated_by, deleted_at FROM mail_accounts 
WHERE direction IN ('inbound', 'both') AND deleted_at IS NULL
`

func (q *Queries) ListInboundMailAccounts(ctx context.Context) ([]MailAccounts, error) {
	rows, err := q.db.Query(ctx, listInboundMailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailAccounts
	for rows.Next() {
		var i MailAccounts
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Address,
			&i.Direction,
			&i.IsDefaultInbound,
			&i.IsDefaultOutbound,
			&i.Protocol,
			&i.CredentialsEncrypted,
			&i.PollIntervalSeconds,
			&i.LastPolledAt,
			&i.LastUid,
			&i.DefaultTeamID,
			&i.DefaultTypeID,
			&i.StripQuotedReply,
			&i.SignatureHtml,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailAccounts = `-- name: ListMailAccounts :many
SELECT id, label, address, direction, is_default_inbound, is_default_outbound, protocol, credentials_encrypted, poll_interval_seconds, last_polled_at, last_uid, default_team_id, default_type_id, strip_quoted_reply, signature_html, created_at, updated_at, created_by, updated_by, deleted_at FROM mail_accounts WHERE deleted_at IS NULL ORDER BY label ASC
`

func (q *Queries) ListMailAccounts(ctx context.Context) ([]MailAccounts, error) {
	rows, err := q.db.Query(ctx, listMailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailAccounts
	for rows.Next() {
		var i MailAccounts
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Address,
			&i.Direction,
			&i.IsDefaultInbound,
			&i.IsDefaultOutbound,
			&i.Protocol,
			&i.CredentialsEncrypted,
			&i.PollIntervalSeconds,
			&i.LastPolledAt,
			&i.LastUid,
			&i.DefaultTeamID,
			&i.DefaultTypeID,
			&i.StripQuotedReply,
			&i.SignatureHtml,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailFilters = `-- name: ListMailFilters :many
SELECT id, mail_account_id, match, action, created_at, updated_at, created_by, updated_by, deleted_at FROM mail_filters WHERE mail_account_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListMailFilters(ctx context.Context, mailAccountID pgtype.UUID) ([]MailFilters, error) {
	rows, err := q.db.Query(ctx, listMailFilters, mailAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailFilters
	for rows.Next() {
		var i MailFilters
		if err := rows.Scan(
			&i.ID,
			&i.MailAccountID,
			&i.Match,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplyTemplates = `-- name: ListReplyTemplates :many
SELECT id, name, scope, owner_agent_id, team_id, subject_template, body_template, attachment_ids, usage_count, is_active, created_at, updated_at, created_by, updated_by, deleted_at FROM reply_templates 
WHERE is_active = TRUE 
  AND deleted_at IS NULL 
  AND (scope = 'global' OR (scope = 'team' AND team_id = $1::uuid) OR (scope = 'personal' AND owner_agent_id = $2::uuid))
ORDER BY usage_count DESC, name ASC
`

type ListReplyTemplatesParams struct {
	TeamID  pgtype.UUID `json:"team_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) ListReplyTemplates(ctx context.Context, arg ListReplyTemplatesParams) ([]ReplyTemplates, error) {
	rows, err := q.db.Query(ctx, listReplyTemplates, arg.TeamID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplyTemplates
	for rows.Next() {
		var i ReplyTemplates
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.OwnerAgentID,
			&i.TeamID,
			&i.SubjectTemplate,
			&i.BodyTemplate,
			&i.AttachmentIds,
			&i.UsageCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAutomationRun = `-- name: RecordAutomationRun :exec
INSERT INTO automation_runs (id, rule_id, ticket_id, status, error, actions_applied)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordAutomationRunParams struct {
	ID             pgtype.UUID `json:"id"`
	RuleID         pgtype.UUID `json:"rule_id"`
	TicketID       pgtype.UUID `json:"ticket_id"`
	Status         string      `json:"status"`
	Error          pgtype.Text `json:"error"`
	ActionsApplied []byte      `json:"actions_applied"`
}

func (q *Queries) RecordAutomationRun(ctx context.Context, arg RecordAutomationRunParams) error {
	_, err := q.db.Exec(ctx, recordAutomationRun,
		arg.ID,
		arg.RuleID,
		arg.TicketID,
		arg.Status,
		arg.Error,
		arg.ActionsApplied,
	)
	return err
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :exec
INSERT INTO webhook_deliveries (id, webhook_id, event, payload, response_code, attempt, next_retry_at, delivered_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordWebhookDeliveryParams struct {
	ID           pgtype.UUID        `json:"id"`
	WebhookID    pgtype.UUID        `json:"webhook_id"`
	Event        string             `json:"event"`
	Payload      []byte             `json:"payload"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	Attempt      int32              `json:"attempt"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, recordWebhookDelivery,
		arg.ID,
		arg.WebhookID,
		arg.Event,
		arg.Payload,
		arg.ResponseCode,
		arg.Attempt,
		arg.NextRetryAt,
		arg.DeliveredAt,
	)
	return err
}

const updateAssignmentRuleLastAgent = `-- name: UpdateAssignmentRuleLastAgent :exec
UPDATE assignment_rules SET last_assigned_agent_id = $2 WHERE id = $1
`

type UpdateAssignmentRuleLastAgentParams struct {
	ID                  pgtype.UUID `json:"id"`
	LastAssignedAgentID pgtype.UUID `json:"last_assigned_agent_id"`
}

func (q *Queries) UpdateAssignmentRuleLastAgent(ctx context.Context, arg UpdateAssignmentRuleLastAgentParams) error {
	_, err := q.db.Exec(ctx, updateAssignmentRuleLastAgent, arg.ID, arg.LastAssignedAgentID)
	return err
}

const updateMailAccountPolled = `-- name: UpdateMailAccountPolled :exec
UPDATE mail_accounts 
SET last_polled_at = (now() AT TIME ZONE 'utc'), last_uid = $2 
WHERE id = $1
`

type UpdateMailAccountPolledParams struct {
	ID      pgtype.UUID `json:"id"`
	LastUid int64       `json:"last_uid"`
}

func (q *Queries) UpdateMailAccountPolled(ctx context.Context, arg UpdateMailAccountPolledParams) error {
	_, err := q.db.Exec(ctx, updateMailAccountPolled, arg.ID, arg.LastUid)
	return err
}
