// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (
    id,
    ticket_id,
    event_id,
    filename,
    mime_type,
    size_bytes,
    storage_key,
    checksum_sha256,
    is_inline,
    content_id,
    scan_status,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
) RETURNING id, ticket_id, event_id, filename, mime_type, size_bytes, storage_key, checksum_sha256, is_inline, content_id, scan_status, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateAttachmentParams struct {
	ID             pgtype.UUID `json:"id"`
	TicketID       pgtype.UUID `json:"ticket_id"`
	EventID        pgtype.UUID `json:"event_id"`
	Filename       string      `json:"filename"`
	MimeType       string      `json:"mime_type"`
	SizeBytes      int64       `json:"size_bytes"`
	StorageKey     string      `json:"storage_key"`
	ChecksumSha256 string      `json:"checksum_sha256"`
	IsInline       bool        `json:"is_inline"`
	ContentID      pgtype.Text `json:"content_id"`
	ScanStatus     string      `json:"scan_status"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachments, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.TicketID,
		arg.EventID,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.ChecksumSha256,
		arg.IsInline,
		arg.ContentID,
		arg.ScanStatus,
		arg.CreatedBy,
	)
	var i Attachments
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.EventID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.ChecksumSha256,
		&i.IsInline,
		&i.ContentID,
		&i.ScanStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const createMention = `-- name: CreateMention :exec
INSERT INTO mentions (id, event_id, agent_id) VALUES ($1, $2, $3)
`

type CreateMentionParams struct {
	ID      pgtype.UUID `json:"id"`
	EventID pgtype.UUID `json:"event_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) error {
	_, err := q.db.Exec(ctx, createMention, arg.ID, arg.EventID, arg.AgentID)
	return err
}

const createTicketEvent = `-- name: CreateTicketEvent :one
INSERT INTO ticket_events (
    id,
    ticket_id,
    kind,
    visibility,
    author_type,
    author_id,
    body_html,
    body_text,
    metadata,
    email_message_id,
    email_in_reply_to,
    email_references,
    delivery_status,
    occurred_at,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
) RETURNING id, ticket_id, kind, visibility, author_type, author_id, body_html, body_text, metadata, email_message_id, email_in_reply_to, email_references, delivery_status, occurred_at, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateTicketEventParams struct {
	ID              pgtype.UUID        `json:"id"`
	TicketID        pgtype.UUID        `json:"ticket_id"`
	Kind            string             `json:"kind"`
	Visibility      string             `json:"visibility"`
	AuthorType      string             `json:"author_type"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	BodyHtml        string             `json:"body_html"`
	BodyText        string             `json:"body_text"`
	Metadata        []byte             `json:"metadata"`
	EmailMessageID  pgtype.Text        `json:"email_message_id"`
	EmailInReplyTo  pgtype.Text        `json:"email_in_reply_to"`
	EmailReferences []string           `json:"email_references"`
	DeliveryStatus  string             `json:"delivery_status"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (TicketEvents, error) {
	row := q.db.QueryRow(ctx, createTicketEvent,
		arg.ID,
		arg.TicketID,
		arg.Kind,
		arg.Visibility,
		arg.AuthorType,
		arg.AuthorID,
		arg.BodyHtml,
		arg.BodyText,
		arg.Metadata,
		arg.EmailMessageID,
		arg.EmailInReplyTo,
		arg.EmailReferences,
		arg.DeliveryStatus,
		arg.OccurredAt,
		arg.CreatedBy,
	)
	var i TicketEvents
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Kind,
		&i.Visibility,
		&i.AuthorType,
		&i.AuthorID,
		&i.BodyHtml,
		&i.BodyText,
		&i.Metadata,
		&i.EmailMessageID,
		&i.EmailInReplyTo,
		&i.EmailReferences,
		&i.DeliveryStatus,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getAttachmentsByTicket = `-- name: GetAttachmentsByTicket :many
SELECT id, ticket_id, event_id, filename, mime_type, size_bytes, storage_key, checksum_sha256, is_inline, content_id, scan_status, created_at, updated_at, created_by, updated_by, deleted_at FROM attachments WHERE ticket_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAttachmentsByTicket(ctx context.Context, ticketID pgtype.UUID) ([]Attachments, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachments
	for rows.Next() {
		var i Attachments
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.EventID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.ChecksumSha256,
			&i.IsInline,
			&i.ContentID,
			&i.ScanStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByEmailMessageID = `-- name: GetEventByEmailMessageID :one
SELECT id, ticket_id, kind, visibility, author_type, author_id, body_html, body_text, metadata, email_message_id, email_in_reply_to, email_references, delivery_status, occurred_at, created_at, updated_at, created_by, updated_by, deleted_at FROM ticket_events WHERE email_message_id = $1 LIMIT 1
`

func (q *Queries) GetEventByEmailMessageID(ctx context.Context, emailMessageID pgtype.Text) (TicketEvents, error) {
	row := q.db.QueryRow(ctx, getEventByEmailMessageID, emailMessageID)
	var i TicketEvents
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Kind,
		&i.Visibility,
		&i.AuthorType,
		&i.AuthorID,
		&i.BodyHtml,
		&i.BodyText,
		&i.Metadata,
		&i.EmailMessageID,
		&i.EmailInReplyTo,
		&i.EmailReferences,
		&i.DeliveryStatus,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listTicketEventsKeyset = `-- name: ListTicketEventsKeyset :many
SELECT 
    e.id,
    e.ticket_id,
    e.kind,
    e.visibility,
    e.author_type,
    e.author_id,
    CASE 
        WHEN e.author_type = 'agent' THEN (SELECT display_name FROM agents WHERE id = e.author_id)
        WHEN e.author_type = 'contact' THEN (SELECT full_name FROM contacts WHERE id = e.author_id)
        ELSE 'System'
    END AS author_name,
    e.body_html,
    e.body_text,
    e.metadata,
    e.email_message_id,
    e.email_in_reply_to,
    e.email_references,
    e.delivery_status,
    e.occurred_at,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'id', att.id,
            'filename', att.filename,
            'mime_type', att.mime_type,
            'size_bytes', att.size_bytes,
            'storage_key', att.storage_key,
            'is_inline', att.is_inline,
            'content_id', att.content_id
        ))
        FROM attachments att
        WHERE att.event_id = e.id),
        '[]'::json
    ) AS attachments_json,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'agent_id', m.agent_id,
            'agent_name', ag.display_name,
            'read_at', m.read_at
        ))
        FROM mentions m
        JOIN agents ag ON ag.id = m.agent_id
        WHERE m.event_id = e.id),
        '[]'::json
    ) AS mentions_json
FROM ticket_events e
WHERE e.ticket_id = $1
  AND ($3::text IS NULL OR $3::text = '' OR e.visibility = $3)
  AND (
    $4::timestamptz IS NULL
    OR (e.occurred_at, e.id) < ($4, $5::uuid)
  )
ORDER BY e.occurred_at DESC, e.id DESC
LIMIT $2
`

type ListTicketEventsKeysetParams struct {
	TicketID        pgtype.UUID        `json:"ticket_id"`
	Limit           int32              `json:"limit"`
	Visibility      pgtype.Text        `json:"visibility"`
	AfterOccurredAt pgtype.Timestamptz `json:"after_occurred_at"`
	AfterID         pgtype.UUID        `json:"after_id"`
}

type ListTicketEventsKeysetRow struct {
	ID              pgtype.UUID        `json:"id"`
	TicketID        pgtype.UUID        `json:"ticket_id"`
	Kind            string             `json:"kind"`
	Visibility      string             `json:"visibility"`
	AuthorType      string             `json:"author_type"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	AuthorName      string             `json:"author_name"`
	BodyHtml        string             `json:"body_html"`
	BodyText        string             `json:"body_text"`
	Metadata        []byte             `json:"metadata"`
	EmailMessageID  pgtype.Text        `json:"email_message_id"`
	EmailInReplyTo  pgtype.Text        `json:"email_in_reply_to"`
	EmailReferences []string           `json:"email_references"`
	DeliveryStatus  string             `json:"delivery_status"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	AttachmentsJson interface{}        `json:"attachments_json"`
	MentionsJson    interface{}        `json:"mentions_json"`
}

// Query 2 of 2 for Ticket Detail: Keyset paginated timeline events with attachments and mentions
func (q *Queries) ListTicketEventsKeyset(ctx context.Context, arg ListTicketEventsKeysetParams) ([]ListTicketEventsKeysetRow, error) {
	rows, err := q.db.Query(ctx, listTicketEventsKeyset,
		arg.TicketID,
		arg.Limit,
		arg.Visibility,
		arg.AfterOccurredAt,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketEventsKeysetRow
	for rows.Next() {
		var i ListTicketEventsKeysetRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Kind,
			&i.Visibility,
			&i.AuthorType,
			&i.AuthorID,
			&i.AuthorName,
			&i.BodyHtml,
			&i.BodyText,
			&i.Metadata,
			&i.EmailMessageID,
			&i.EmailInReplyTo,
			&i.EmailReferences,
			&i.DeliveryStatus,
			&i.OccurredAt,
			&i.AttachmentsJson,
			&i.MentionsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMentionRead = `-- name: MarkMentionRead :exec
UPDATE mentions SET read_at = (now() AT TIME ZONE 'utc') WHERE event_id = $1 AND agent_id = $2
`

type MarkMentionReadParams struct {
	EventID pgtype.UUID `json:"event_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) MarkMentionRead(ctx context.Context, arg MarkMentionReadParams) error {
	_, err := q.db.Exec(ctx, markMentionRead, arg.EventID, arg.AgentID)
	return err
}
