// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: kb.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getKBArticleBySlug = `-- name: GetKBArticleBySlug :one
SELECT 
    a.id,
    a.category_id,
    a.slug,
    a.title,
    a.status,
    a.locale,
    a.body_html,
    a.body_text,
    a.excerpt,
    a.author_id,
    a.reviewer_id,
    a.published_at,
    a.view_count,
    a.helpful_count,
    a.unhelpful_count,
    a.keywords,
    a.translation_of_id,
    a.created_at,
    a.updated_at,
    a.created_by,
    a.updated_by,
    a.deleted_at,
    c.name AS category_name,
    c.slug AS category_slug,
    s.name AS space_name,
    s.slug AS space_slug
FROM kb_articles a
JOIN kb_categories c ON c.id = a.category_id
JOIN kb_spaces s ON s.id = c.space_id
WHERE a.slug = $1 AND a.deleted_at IS NULL
`

type GetKBArticleBySlugRow struct {
	ID              pgtype.UUID        `json:"id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Status          string             `json:"status"`
	Locale          string             `json:"locale"`
	BodyHtml        string             `json:"body_html"`
	BodyText        string             `json:"body_text"`
	Excerpt         pgtype.Text        `json:"excerpt"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ViewCount       int32              `json:"view_count"`
	HelpfulCount    int32              `json:"helpful_count"`
	UnhelpfulCount  int32              `json:"unhelpful_count"`
	Keywords        []string           `json:"keywords"`
	TranslationOfID pgtype.UUID        `json:"translation_of_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CategoryName    string             `json:"category_name"`
	CategorySlug    string             `json:"category_slug"`
	SpaceName       string             `json:"space_name"`
	SpaceSlug       string             `json:"space_slug"`
}

func (q *Queries) GetKBArticleBySlug(ctx context.Context, slug string) (GetKBArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getKBArticleBySlug, slug)
	var i GetKBArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Locale,
		&i.BodyHtml,
		&i.BodyText,
		&i.Excerpt,
		&i.AuthorID,
		&i.ReviewerID,
		&i.PublishedAt,
		&i.ViewCount,
		&i.HelpfulCount,
		&i.UnhelpfulCount,
		&i.Keywords,
		&i.TranslationOfID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.CategoryName,
		&i.CategorySlug,
		&i.SpaceName,
		&i.SpaceSlug,
	)
	return i, err
}

const incrementArticleViewCount = `-- name: IncrementArticleViewCount :exec
UPDATE kb_articles SET view_count = view_count + 1 WHERE kb_articles.id = $1
`

func (q *Queries) IncrementArticleViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementArticleViewCount, id)
	return err
}

const listKBArticlesByCategory = `-- name: ListKBArticlesByCategory :many
SELECT 
    id, category_id, slug, title, status, locale, excerpt, author_id, published_at, view_count, helpful_count, unhelpful_count
FROM kb_articles
WHERE category_id = $1 
  AND ($2::text IS NULL OR status = $2)
  AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST, title ASC
`

type ListKBArticlesByCategoryParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Column2    string      `json:"column_2"`
}

type ListKBArticlesByCategoryRow struct {
	ID             pgtype.UUID        `json:"id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	Locale         string             `json:"locale"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	ViewCount      int32              `json:"view_count"`
	HelpfulCount   int32              `json:"helpful_count"`
	UnhelpfulCount int32              `json:"unhelpful_count"`
}

func (q *Queries) ListKBArticlesByCategory(ctx context.Context, arg ListKBArticlesByCategoryParams) ([]ListKBArticlesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listKBArticlesByCategory, arg.CategoryID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKBArticlesByCategoryRow
	for rows.Next() {
		var i ListKBArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Locale,
			&i.Excerpt,
			&i.AuthorID,
			&i.PublishedAt,
			&i.ViewCount,
			&i.HelpfulCount,
			&i.UnhelpfulCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBCategoriesBySpace = `-- name: ListKBCategoriesBySpace :many
SELECT 
    c.id, c.space_id, c.parent_id, c.name, c.slug, c.sort_order, c.created_at, c.updated_at, c.created_by, c.updated_by, c.deleted_at,
    (SELECT count(*) FROM kb_articles a WHERE a.category_id = c.id AND a.status = 'published' AND a.deleted_at IS NULL) AS published_article_count
FROM kb_categories c
WHERE c.space_id = $1 AND c.deleted_at IS NULL
ORDER BY c.sort_order ASC, c.name ASC
`

type ListKBCategoriesBySpaceRow struct {
	ID                    pgtype.UUID        `json:"id"`
	SpaceID               pgtype.UUID        `json:"space_id"`
	ParentID              pgtype.UUID        `json:"parent_id"`
	Name                  string             `json:"name"`
	Slug                  string             `json:"slug"`
	SortOrder             int32              `json:"sort_order"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	UpdatedBy             pgtype.UUID        `json:"updated_by"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	PublishedArticleCount int64              `json:"published_article_count"`
}

func (q *Queries) ListKBCategoriesBySpace(ctx context.Context, spaceID pgtype.UUID) ([]ListKBCategoriesBySpaceRow, error) {
	rows, err := q.db.Query(ctx, listKBCategoriesBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKBCategoriesBySpaceRow
	for rows.Next() {
		var i ListKBCategoriesBySpaceRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.PublishedArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBSpaces = `-- name: ListKBSpaces :many
SELECT id, name, slug, visibility, created_at, updated_at, created_by, updated_by, deleted_at FROM kb_spaces WHERE deleted_at IS NULL ORDER BY name ASC
`

func (q *Queries) ListKBSpaces(ctx context.Context) ([]KbSpaces, error) {
	rows, err := q.db.Query(ctx, listKBSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KbSpaces
	for rows.Next() {
		var i KbSpaces
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordArticleFeedback = `-- name: RecordArticleFeedback :exec
INSERT INTO kb_feedback (id, article_id, contact_id, is_helpful, comment)
VALUES ($1, $2, $3, $4, $5)
`

type RecordArticleFeedbackParams struct {
	ID        pgtype.UUID `json:"id"`
	ArticleID pgtype.UUID `json:"article_id"`
	ContactID pgtype.UUID `json:"contact_id"`
	IsHelpful bool        `json:"is_helpful"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) RecordArticleFeedback(ctx context.Context, arg RecordArticleFeedbackParams) error {
	_, err := q.db.Exec(ctx, recordArticleFeedback,
		arg.ID,
		arg.ArticleID,
		arg.ContactID,
		arg.IsHelpful,
		arg.Comment,
	)
	return err
}

const searchKBArticles = `-- name: SearchKBArticles :many
SELECT 
    a.id,
    a.category_id,
    a.slug,
    a.title,
    a.excerpt,
    a.status,
    a.locale,
    ts_rank_cd(a.search_vector, websearch_to_tsquery('english', $1)) AS rank,
    c.name AS category_name,
    s.name AS space_name
FROM kb_articles a
JOIN kb_categories c ON c.id = a.category_id
JOIN kb_spaces s ON s.id = c.space_id
WHERE a.status = 'published' 
  AND a.deleted_at IS NULL
  AND a.search_vector @@ websearch_to_tsquery('english', $1)
ORDER BY rank DESC
LIMIT $2
`

type SearchKBArticlesParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
}

type SearchKBArticlesRow struct {
	ID           pgtype.UUID `json:"id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	Excerpt      pgtype.Text `json:"excerpt"`
	Status       string      `json:"status"`
	Locale       string      `json:"locale"`
	Rank         float32     `json:"rank"`
	CategoryName string      `json:"category_name"`
	SpaceName    string      `json:"space_name"`
}

func (q *Queries) SearchKBArticles(ctx context.Context, arg SearchKBArticlesParams) ([]SearchKBArticlesRow, error) {
	rows, err := q.db.Query(ctx, searchKBArticles, arg.WebsearchToTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchKBArticlesRow
	for rows.Next() {
		var i SearchKBArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Status,
			&i.Locale,
			&i.Rank,
			&i.CategoryName,
			&i.SpaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticleHelpfulScore = `-- name: UpdateArticleHelpfulScore :exec
UPDATE kb_articles 
SET 
    helpful_count = (SELECT count(*) FROM kb_feedback kbf WHERE kbf.article_id = $1 AND kbf.is_helpful = TRUE),
    unhelpful_count = (SELECT count(*) FROM kb_feedback kbf WHERE kbf.article_id = $1 AND kbf.is_helpful = FALSE)
WHERE kb_articles.id = $1
`

func (q *Queries) UpdateArticleHelpfulScore(ctx context.Context, articleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateArticleHelpfulScore, articleID)
	return err
}
