// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agents struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	DisplayName          string             `json:"display_name"`
	SignatureHtml        string             `json:"signature_html"`
	IsAvailable          bool               `json:"is_available"`
	MaxConcurrentTickets int32              `json:"max_concurrent_tickets"`
	Skills               []string           `json:"skills"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type AssignmentRules struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	IsActive            bool               `json:"is_active"`
	PriorityOrder       int32              `json:"priority_order"`
	Trigger             string             `json:"trigger"`
	MatchConditions     []byte             `json:"match_conditions"`
	Strategy            string             `json:"strategy"`
	TargetTeamID        pgtype.UUID        `json:"target_team_id"`
	CandidateAgentIds   []pgtype.UUID      `json:"candidate_agent_ids"`
	ActiveWeekdays      []int32            `json:"active_weekdays"`
	ActiveFromTime      pgtype.Time        `json:"active_from_time"`
	ActiveToTime        pgtype.Time        `json:"active_to_time"`
	RespectAvailability bool               `json:"respect_availability"`
	RespectCapacity     bool               `json:"respect_capacity"`
	LastAssignedAgentID pgtype.UUID        `json:"last_assigned_agent_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Attachments struct {
	ID             pgtype.UUID        `json:"id"`
	TicketID       pgtype.UUID        `json:"ticket_id"`
	EventID        pgtype.UUID        `json:"event_id"`
	Filename       string             `json:"filename"`
	MimeType       string             `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	StorageKey     string             `json:"storage_key"`
	ChecksumSha256 string             `json:"checksum_sha256"`
	IsInline       bool               `json:"is_inline"`
	ContentID      pgtype.Text        `json:"content_id"`
	ScanStatus     string             `json:"scan_status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ActorType string             `json:"actor_type"`
	Entity    string             `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Action    string             `json:"action"`
	Before    []byte             `json:"before"`
	After     []byte             `json:"after"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
	At        pgtype.Timestamptz `json:"at"`
}

type AutomationRules struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	IsActive         bool               `json:"is_active"`
	PriorityOrder    int32              `json:"priority_order"`
	Trigger          string             `json:"trigger"`
	MatchConditions  []byte             `json:"match_conditions"`
	Actions          []byte             `json:"actions"`
	RunOncePerTicket bool               `json:"run_once_per_ticket"`
	ScheduleCron     pgtype.Text        `json:"schedule_cron"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type AutomationRuns struct {
	ID             pgtype.UUID        `json:"id"`
	RuleID         pgtype.UUID        `json:"rule_id"`
	TicketID       pgtype.UUID        `json:"ticket_id"`
	Status         string             `json:"status"`
	Error          pgtype.Text        `json:"error"`
	ActionsApplied []byte             `json:"actions_applied"`
	RanAt          pgtype.Timestamptz `json:"ran_at"`
}

type BusinessHourSlots struct {
	ID              pgtype.UUID        `json:"id"`
	BusinessHoursID pgtype.UUID        `json:"business_hours_id"`
	Weekday         int32              `json:"weekday"`
	StartTime       pgtype.Time        `json:"start_time"`
	EndTime         pgtype.Time        `json:"end_time"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type BusinessHours struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ContactEmails struct {
	ID         pgtype.UUID        `json:"id"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	Email      string             `json:"email"`
	IsPrimary  bool               `json:"is_primary"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Contacts struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	PrimaryEmail   string             `json:"primary_email"`
	FullName       string             `json:"full_name"`
	Phone          pgtype.Text        `json:"phone"`
	Locale         string             `json:"locale"`
	Timezone       string             `json:"timezone"`
	IsVerified     bool               `json:"is_verified"`
	PortalUserID   pgtype.UUID        `json:"portal_user_id"`
	CustomData     []byte             `json:"custom_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type FieldDefinitions struct {
	ID               pgtype.UUID        `json:"id"`
	Entity           string             `json:"entity"`
	Key              string             `json:"key"`
	Label            string             `json:"label"`
	DataType         string             `json:"data_type"`
	Options          []byte             `json:"options"`
	IsRequired       bool               `json:"is_required"`
	IsAgentOnly      bool               `json:"is_agent_only"`
	ShowInPortalForm bool               `json:"show_in_portal_form"`
	ShowInList       bool               `json:"show_in_list"`
	DefaultValue     pgtype.Text        `json:"default_value"`
	ValidationRegex  pgtype.Text        `json:"validation_regex"`
	DependsOn        []byte             `json:"depends_on"`
	SortOrder        int32              `json:"sort_order"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type HolidayCalendars struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Holidays struct {
	ID                pgtype.UUID        `json:"id"`
	CalendarID        pgtype.UUID        `json:"calendar_id"`
	Date              pgtype.Date        `json:"date"`
	Label             string             `json:"label"`
	IsRecurringAnnual bool               `json:"is_recurring_annual"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type KbArticleVersions struct {
	ID         pgtype.UUID        `json:"id"`
	ArticleID  pgtype.UUID        `json:"article_id"`
	Version    int32              `json:"version"`
	Title      string             `json:"title"`
	BodyHtml   string             `json:"body_html"`
	ChangedBy  pgtype.UUID        `json:"changed_by"`
	ChangeNote pgtype.Text        `json:"change_note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type KbArticles struct {
	ID              pgtype.UUID        `json:"id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Status          string             `json:"status"`
	Locale          string             `json:"locale"`
	BodyHtml        string             `json:"body_html"`
	BodyText        string             `json:"body_text"`
	Excerpt         pgtype.Text        `json:"excerpt"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	ReviewerID      pgtype.UUID        `json:"reviewer_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ViewCount       int32              `json:"view_count"`
	HelpfulCount    int32              `json:"helpful_count"`
	UnhelpfulCount  int32              `json:"unhelpful_count"`
	Keywords        []string           `json:"keywords"`
	SearchVector    interface{}        `json:"search_vector"`
	TranslationOfID pgtype.UUID        `json:"translation_of_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type KbCategories struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type KbFeedback struct {
	ID        pgtype.UUID        `json:"id"`
	ArticleID pgtype.UUID        `json:"article_id"`
	ContactID pgtype.UUID        `json:"contact_id"`
	IsHelpful bool               `json:"is_helpful"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type KbSpaces struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	Visibility string             `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type MailAccounts struct {
	ID                   pgtype.UUID        `json:"id"`
	Label                string             `json:"label"`
	Address              string             `json:"address"`
	Direction            string             `json:"direction"`
	IsDefaultInbound     bool               `json:"is_default_inbound"`
	IsDefaultOutbound    bool               `json:"is_default_outbound"`
	Protocol             string             `json:"protocol"`
	CredentialsEncrypted string             `json:"credentials_encrypted"`
	PollIntervalSeconds  int32              `json:"poll_interval_seconds"`
	LastPolledAt         pgtype.Timestamptz `json:"last_polled_at"`
	LastUid              int64              `json:"last_uid"`
	DefaultTeamID        pgtype.UUID        `json:"default_team_id"`
	DefaultTypeID        pgtype.UUID        `json:"default_type_id"`
	StripQuotedReply     bool               `json:"strip_quoted_reply"`
	SignatureHtml        string             `json:"signature_html"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type MailFilters struct {
	ID            pgtype.UUID        `json:"id"`
	MailAccountID pgtype.UUID        `json:"mail_account_id"`
	Match         []byte             `json:"match"`
	Action        []byte             `json:"action"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	UpdatedBy     pgtype.UUID        `json:"updated_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type MailSuppressions struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Mentions struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationPrefs struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Channel   string             `json:"channel"`
	EventKey  string             `json:"event_key"`
	IsEnabled bool               `json:"is_enabled"`
	Digest    string             `json:"digest"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Notifications struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	EventKey  string             `json:"event_key"`
	TicketID  pgtype.UUID        `json:"ticket_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	ActionUrl pgtype.Text        `json:"action_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Organizations struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Domain          pgtype.Text        `json:"domain"`
	DefaultTimezone string             `json:"default_timezone"`
	Settings        []byte             `json:"settings"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Outbox struct {
	ID          pgtype.UUID        `json:"id"`
	Aggregate   string             `json:"aggregate"`
	AggregateID pgtype.UUID        `json:"aggregate_id"`
	Event       string             `json:"event"`
	Payload     []byte             `json:"payload"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	RetryCount  int32              `json:"retry_count"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Permissions struct {
	ID          pgtype.UUID `json:"id"`
	Key         string      `json:"key"`
	Label       string      `json:"label"`
	Description pgtype.Text `json:"description"`
}

type ReplyTemplates struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Scope           string             `json:"scope"`
	OwnerAgentID    pgtype.UUID        `json:"owner_agent_id"`
	TeamID          pgtype.UUID        `json:"team_id"`
	SubjectTemplate string             `json:"subject_template"`
	BodyTemplate    string             `json:"body_template"`
	AttachmentIds   []pgtype.UUID      `json:"attachment_ids"`
	UsageCount      int32              `json:"usage_count"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type RolePermissions struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type Roles struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Label       string             `json:"label"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type SavedViews struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Entity     string             `json:"entity"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	Visibility string             `json:"visibility"`
	TeamID     pgtype.UUID        `json:"team_id"`
	Filters    []byte             `json:"filters"`
	Columns    []byte             `json:"columns"`
	Sort       []byte             `json:"sort"`
	GroupBy    pgtype.Text        `json:"group_by"`
	IsPinned   bool               `json:"is_pinned"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	UpdatedBy  pgtype.UUID        `json:"updated_by"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type SlaEscalations struct {
	ID            pgtype.UUID        `json:"id"`
	PolicyID      pgtype.UUID        `json:"policy_id"`
	Target        string             `json:"target"`
	TriggerAtPct  pgtype.Int4        `json:"trigger_at_pct"`
	OffsetMinutes pgtype.Int4        `json:"offset_minutes"`
	Actions       []byte             `json:"actions"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	UpdatedBy     pgtype.UUID        `json:"updated_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type SlaPolicies struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	IsActive          bool               `json:"is_active"`
	PriorityOrder     int32              `json:"priority_order"`
	MatchConditions   []byte             `json:"match_conditions"`
	BusinessHoursID   pgtype.UUID        `json:"business_hours_id"`
	HolidayCalendarID pgtype.UUID        `json:"holiday_calendar_id"`
	ApplyTo           string             `json:"apply_to"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type SlaTargets struct {
	ID                   pgtype.UUID        `json:"id"`
	PolicyID             pgtype.UUID        `json:"policy_id"`
	PriorityID           pgtype.UUID        `json:"priority_id"`
	FirstResponseMinutes int32              `json:"first_response_minutes"`
	ResolutionMinutes    int32              `json:"resolution_minutes"`
	NextResponseMinutes  pgtype.Int4        `json:"next_response_minutes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type Tags struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type TeamMembers struct {
	ID        pgtype.UUID        `json:"id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Teams struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Slug               string             `json:"slug"`
	LeadAgentID        pgtype.UUID        `json:"lead_agent_id"`
	InboxEmail         pgtype.Text        `json:"inbox_email"`
	AssignmentStrategy string             `json:"assignment_strategy"`
	RestrictVisibility bool               `json:"restrict_visibility"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type TicketEvents struct {
	ID              pgtype.UUID        `json:"id"`
	TicketID        pgtype.UUID        `json:"ticket_id"`
	Kind            string             `json:"kind"`
	Visibility      string             `json:"visibility"`
	AuthorType      string             `json:"author_type"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	BodyHtml        string             `json:"body_html"`
	BodyText        string             `json:"body_text"`
	Metadata        []byte             `json:"metadata"`
	EmailMessageID  pgtype.Text        `json:"email_message_id"`
	EmailInReplyTo  pgtype.Text        `json:"email_in_reply_to"`
	EmailReferences []string           `json:"email_references"`
	DeliveryStatus  string             `json:"delivery_status"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	UpdatedBy       pgtype.UUID        `json:"updated_by"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type TicketLinks struct {
	FromTicketID pgtype.UUID        `json:"from_ticket_id"`
	ToTicketID   pgtype.UUID        `json:"to_ticket_id"`
	Relation     string             `json:"relation"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TicketPriorities struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	Weight    int32              `json:"weight"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type TicketStatuses struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	Label     string             `json:"label"`
	Category  string             `json:"category"`
	PausesSla bool               `json:"pauses_sla"`
	StopsSla  bool               `json:"stops_sla"`
	IsDefault bool               `json:"is_default"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type TicketTags struct {
	TicketID  pgtype.UUID        `json:"ticket_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TicketTypes struct {
	ID                pgtype.UUID        `json:"id"`
	Key               string             `json:"key"`
	Label             string             `json:"label"`
	DefaultPriorityID pgtype.UUID        `json:"default_priority_id"`
	DefaultTeamID     pgtype.UUID        `json:"default_team_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type TicketWatchers struct {
	TicketID  pgtype.UUID        `json:"ticket_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tickets struct {
	ID                     pgtype.UUID        `json:"id"`
	ReferenceNo            string             `json:"reference_no"`
	Subject                string             `json:"subject"`
	DescriptionHtml        string             `json:"description_html"`
	DescriptionText        string             `json:"description_text"`
	StatusID               pgtype.UUID        `json:"status_id"`
	StatusCategory         string             `json:"status_category"`
	PriorityID             pgtype.UUID        `json:"priority_id"`
	PriorityWeight         int32              `json:"priority_weight"`
	TypeID                 pgtype.UUID        `json:"type_id"`
	ContactID              pgtype.UUID        `json:"contact_id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	AssignedAgentID        pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID         pgtype.UUID        `json:"assigned_team_id"`
	Source                 string             `json:"source"`
	SlaPolicyID            pgtype.UUID        `json:"sla_policy_id"`
	FirstResponseDueAt     pgtype.Timestamptz `json:"first_response_due_at"`
	FirstRespondedAt       pgtype.Timestamptz `json:"first_responded_at"`
	ResolutionDueAt        pgtype.Timestamptz `json:"resolution_due_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	SlaPausedAt            pgtype.Timestamptz `json:"sla_paused_at"`
	SlaPausedMs            int64              `json:"sla_paused_ms"`
	FirstResponseBreached  bool               `json:"first_response_breached"`
	ResolutionBreached     bool               `json:"resolution_breached"`
	ReopenCount            int32              `json:"reopen_count"`
	MergedIntoID           pgtype.UUID        `json:"merged_into_id"`
	ParentTicketID         pgtype.UUID        `json:"parent_ticket_id"`
	LastCustomerActivityAt pgtype.Timestamptz `json:"last_customer_activity_at"`
	LastAgentActivityAt    pgtype.Timestamptz `json:"last_agent_activity_at"`
	FeedbackRating         pgtype.Int4        `json:"feedback_rating"`
	FeedbackComment        pgtype.Text        `json:"feedback_comment"`
	CustomData             []byte             `json:"custom_data"`
	SearchVector           interface{}        `json:"search_vector"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

type UserRoles struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

type Users struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Timezone     string             `json:"timezone"`
	Locale       string             `json:"locale"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	MfaSecret    pgtype.Text        `json:"mfa_secret"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type WebhookDeliveries struct {
	ID           pgtype.UUID        `json:"id"`
	WebhookID    pgtype.UUID        `json:"webhook_id"`
	Event        string             `json:"event"`
	Payload      []byte             `json:"payload"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	Attempt      int32              `json:"attempt"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Webhooks struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Url         string             `json:"url"`
	Secret      string             `json:"secret"`
	Events      []string           `json:"events"`
	IsActive    bool               `json:"is_active"`
	Headers     []byte             `json:"headers"`
	RetryPolicy []byte             `json:"retry_policy"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
