// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimUnpublishedOutboxBatch = `-- name: ClaimUnpublishedOutboxBatch :many
SELECT id, aggregate, aggregate_id, event, payload, published_at, retry_count, last_error, created_at FROM outbox
WHERE published_at IS NULL AND retry_count < 10
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimUnpublishedOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Aggregate,
			&i.AggregateID,
			&i.Event,
			&i.Payload,
			&i.PublishedAt,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :one
INSERT INTO outbox (
    id,
    aggregate,
    aggregate_id,
    event,
    payload
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, aggregate, aggregate_id, event, payload, published_at, retry_count, last_error, created_at
`

type InsertOutboxMessageParams struct {
	ID          pgtype.UUID `json:"id"`
	Aggregate   string      `json:"aggregate"`
	AggregateID pgtype.UUID `json:"aggregate_id"`
	Event       string      `json:"event"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxMessage,
		arg.ID,
		arg.Aggregate,
		arg.AggregateID,
		arg.Event,
		arg.Payload,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.Aggregate,
		&i.AggregateID,
		&i.Event,
		&i.Payload,
		&i.PublishedAt,
		&i.RetryCount,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE outbox
SET retry_count = retry_count + 1,
    last_error = $2
WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox
SET published_at = (now() AT TIME ZONE 'utc')
WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}
