// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMailSuppression(ctx context.Context, arg AddMailSuppressionParams) error
	AddTicketTag(ctx context.Context, arg AddTicketTagParams) error
	AddTicketWatcher(ctx context.Context, arg AddTicketWatcherParams) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	ClaimUnpublishedOutboxBatch(ctx context.Context, limit int32) ([]Outbox, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agents, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachments, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contacts, error)
	CreateMention(ctx context.Context, arg CreateMentionParams) error
	CreateTicket(ctx context.Context, arg CreateTicketParams) (CreateTicketRow, error)
	CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (TicketEvents, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	GetAgentByUserID(ctx context.Context, userID pgtype.UUID) (Agents, error)
	GetAttachmentsByTicket(ctx context.Context, ticketID pgtype.UUID) ([]Attachments, error)
	GetBusinessHoursWithSlots(ctx context.Context, id pgtype.UUID) (GetBusinessHoursWithSlotsRow, error)
	GetContactByEmail(ctx context.Context, primaryEmail string) (Contacts, error)
	GetContactByID(ctx context.Context, id pgtype.UUID) (Contacts, error)
	GetEventByEmailMessageID(ctx context.Context, emailMessageID pgtype.Text) (TicketEvents, error)
	GetHolidayCalendarWithHolidays(ctx context.Context, id pgtype.UUID) (GetHolidayCalendarWithHolidaysRow, error)
	GetKBArticleBySlug(ctx context.Context, slug string) (GetKBArticleBySlugRow, error)
	GetOrCreateOrganizationByDomain(ctx context.Context, arg GetOrCreateOrganizationByDomainParams) (Organizations, error)
	GetRoleByKey(ctx context.Context, key string) (Roles, error)
	GetSLAPolicyEscalations(ctx context.Context, policyID pgtype.UUID) ([]SlaEscalations, error)
	GetSLAPolicyTargets(ctx context.Context, policyID pgtype.UUID) ([]SlaTargets, error)
	GetTicketByReferenceNo(ctx context.Context, referenceNo string) (GetTicketByReferenceNoRow, error)
	// Query 1 of 2 for Ticket Detail: Full Ticket metadata with associations
	GetTicketDetail(ctx context.Context, id pgtype.UUID) (GetTicketDetailRow, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error)
	GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]string, error)
	GetUserRoleKeys(ctx context.Context, userID pgtype.UUID) ([]string, error)
	IncrementArticleViewCount(ctx context.Context, id pgtype.UUID) error
	IncrementReplyTemplateUsage(ctx context.Context, id pgtype.UUID) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) (Outbox, error)
	IsEmailSuppressed(ctx context.Context, email string) (bool, error)
	LinkTickets(ctx context.Context, arg LinkTicketsParams) error
	ListActiveAssignmentRules(ctx context.Context, trigger string) ([]AssignmentRules, error)
	ListActiveAutomationRulesByTrigger(ctx context.Context, trigger string) ([]AutomationRules, error)
	ListActiveSLAPolicies(ctx context.Context) ([]ListActiveSLAPoliciesRow, error)
	ListActiveWebhooksForEvent(ctx context.Context, events []string) ([]Webhooks, error)
	ListAgents(ctx context.Context) ([]ListAgentsRow, error)
	ListAllFieldDefinitions(ctx context.Context) ([]FieldDefinitions, error)
	ListAssignmentRules(ctx context.Context) ([]AssignmentRules, error)
	ListAuditLogsKeyset(ctx context.Context, arg ListAuditLogsKeysetParams) ([]AuditLog, error)
	ListAutomationRules(ctx context.Context) ([]AutomationRules, error)
	ListFieldDefinitions(ctx context.Context, entity string) ([]FieldDefinitions, error)
	ListInboundMailAccounts(ctx context.Context) ([]MailAccounts, error)
	ListKBArticlesByCategory(ctx context.Context, arg ListKBArticlesByCategoryParams) ([]ListKBArticlesByCategoryRow, error)
	ListKBCategoriesBySpace(ctx context.Context, spaceID pgtype.UUID) ([]ListKBCategoriesBySpaceRow, error)
	ListKBSpaces(ctx context.Context) ([]KbSpaces, error)
	ListMailAccounts(ctx context.Context) ([]MailAccounts, error)
	ListMailFilters(ctx context.Context, mailAccountID pgtype.UUID) ([]MailFilters, error)
	ListReplyTemplates(ctx context.Context, arg ListReplyTemplatesParams) ([]ReplyTemplates, error)
	ListTeams(ctx context.Context) ([]ListTeamsRow, error)
	// Query 2 of 2 for Ticket Detail: Keyset paginated timeline events with attachments and mentions
	ListTicketEventsKeyset(ctx context.Context, arg ListTicketEventsKeysetParams) ([]ListTicketEventsKeysetRow, error)
	// 1 Query Ticket List with Keyset Pagination and complete aggregated details
	ListTicketsKeyset(ctx context.Context, arg ListTicketsKeysetParams) ([]ListTicketsKeysetRow, error)
	MarkFirstResponseBreached(ctx context.Context, id pgtype.UUID) error
	MarkMentionRead(ctx context.Context, arg MarkMentionReadParams) error
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error
	MarkOutboxPublished(ctx context.Context, id pgtype.UUID) error
	MarkResolutionBreached(ctx context.Context, id pgtype.UUID) error
	RecordArticleFeedback(ctx context.Context, arg RecordArticleFeedbackParams) error
	RecordAutomationRun(ctx context.Context, arg RecordAutomationRunParams) error
	RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) error
	RemoveTicketTag(ctx context.Context, arg RemoveTicketTagParams) error
	RemoveTicketWatcher(ctx context.Context, arg RemoveTicketWatcherParams) error
	// Uses the partial index: tickets(first_response_due_at) WHERE first_responded_at IS NULL AND sla_paused_at IS NULL AND deleted_at IS NULL
	ScanBreachingFirstResponseTickets(ctx context.Context, arg ScanBreachingFirstResponseTicketsParams) ([]ScanBreachingFirstResponseTicketsRow, error)
	// Uses the partial index: tickets(resolution_due_at) WHERE resolved_at IS NULL AND sla_paused_at IS NULL AND deleted_at IS NULL
	ScanBreachingResolutionTickets(ctx context.Context, arg ScanBreachingResolutionTicketsParams) ([]ScanBreachingResolutionTicketsRow, error)
	SearchKBArticles(ctx context.Context, arg SearchKBArticlesParams) ([]SearchKBArticlesRow, error)
	SoftDeleteTicket(ctx context.Context, arg SoftDeleteTicketParams) error
	UnlinkTickets(ctx context.Context, arg UnlinkTicketsParams) error
	UpdateArticleHelpfulScore(ctx context.Context, articleID pgtype.UUID) error
	UpdateAssignmentRuleLastAgent(ctx context.Context, arg UpdateAssignmentRuleLastAgentParams) error
	UpdateMailAccountPolled(ctx context.Context, arg UpdateMailAccountPolledParams) error
	UpdateTicketFields(ctx context.Context, arg UpdateTicketFieldsParams) (UpdateTicketFieldsRow, error)
}

var _ Querier = (*Queries)(nil)
