// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sla.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBusinessHoursWithSlots = `-- name: GetBusinessHoursWithSlots :one
SELECT 
    bh.id,
    bh.name,
    bh.timezone,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'weekday', bhs.weekday,
            'start_time', bhs.start_time::text,
            'end_time', bhs.end_time::text
        ) ORDER BY bhs.weekday, bhs.start_time)
        FROM business_hour_slots bhs
        WHERE bhs.business_hours_id = bh.id),
        '[]'::json
    ) AS slots_json
FROM business_hours bh
WHERE bh.id = $1 AND bh.deleted_at IS NULL
`

type GetBusinessHoursWithSlotsRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Timezone  string      `json:"timezone"`
	SlotsJson interface{} `json:"slots_json"`
}

func (q *Queries) GetBusinessHoursWithSlots(ctx context.Context, id pgtype.UUID) (GetBusinessHoursWithSlotsRow, error) {
	row := q.db.QueryRow(ctx, getBusinessHoursWithSlots, id)
	var i GetBusinessHoursWithSlotsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.SlotsJson,
	)
	return i, err
}

const getHolidayCalendarWithHolidays = `-- name: GetHolidayCalendarWithHolidays :one
SELECT 
    hc.id,
    hc.name,
    hc.timezone,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'date', h.date::text,
            'label', h.label,
            'is_recurring_annual', h.is_recurring_annual
        ))
        FROM holidays h
        WHERE h.calendar_id = hc.id),
        '[]'::json
    ) AS holidays_json
FROM holiday_calendars hc
WHERE hc.id = $1 AND hc.deleted_at IS NULL
`

type GetHolidayCalendarWithHolidaysRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Timezone     string      `json:"timezone"`
	HolidaysJson interface{} `json:"holidays_json"`
}

func (q *Queries) GetHolidayCalendarWithHolidays(ctx context.Context, id pgtype.UUID) (GetHolidayCalendarWithHolidaysRow, error) {
	row := q.db.QueryRow(ctx, getHolidayCalendarWithHolidays, id)
	var i GetHolidayCalendarWithHolidaysRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.HolidaysJson,
	)
	return i, err
}

const getSLAPolicyEscalations = `-- name: GetSLAPolicyEscalations :many
SELECT id, policy_id, target, trigger_at_pct, offset_minutes, actions, created_at, updated_at, created_by, updated_by, deleted_at FROM sla_escalations WHERE policy_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSLAPolicyEscalations(ctx context.Context, policyID pgtype.UUID) ([]SlaEscalations, error) {
	rows, err := q.db.Query(ctx, getSLAPolicyEscalations, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaEscalations
	for rows.Next() {
		var i SlaEscalations
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Target,
			&i.TriggerAtPct,
			&i.OffsetMinutes,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSLAPolicyTargets = `-- name: GetSLAPolicyTargets :many
SELECT id, policy_id, priority_id, first_response_minutes, resolution_minutes, next_response_minutes, created_at, updated_at, created_by, updated_by, deleted_at FROM sla_targets WHERE policy_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSLAPolicyTargets(ctx context.Context, policyID pgtype.UUID) ([]SlaTargets, error) {
	rows, err := q.db.Query(ctx, getSLAPolicyTargets, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaTargets
	for rows.Next() {
		var i SlaTargets
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.PriorityID,
			&i.FirstResponseMinutes,
			&i.ResolutionMinutes,
			&i.NextResponseMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSLAPolicies = `-- name: ListActiveSLAPolicies :many
SELECT 
    sp.id,
    sp.name,
    sp.priority_order,
    sp.match_conditions,
    sp.business_hours_id,
    sp.holiday_calendar_id,
    sp.apply_to,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'priority_id', st.priority_id,
            'first_response_minutes', st.first_response_minutes,
            'resolution_minutes', st.resolution_minutes,
            'next_response_minutes', st.next_response_minutes
        ))
        FROM sla_targets st
        WHERE st.policy_id = sp.id),
        '[]'::json
    ) AS targets_json
FROM sla_policies sp
WHERE sp.is_active = TRUE AND sp.deleted_at IS NULL
ORDER BY sp.priority_order ASC
`

type ListActiveSLAPoliciesRow struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	PriorityOrder     int32       `json:"priority_order"`
	MatchConditions   []byte      `json:"match_conditions"`
	BusinessHoursID   pgtype.UUID `json:"business_hours_id"`
	HolidayCalendarID pgtype.UUID `json:"holiday_calendar_id"`
	ApplyTo           string      `json:"apply_to"`
	TargetsJson       interface{} `json:"targets_json"`
}

func (q *Queries) ListActiveSLAPolicies(ctx context.Context) ([]ListActiveSLAPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listActiveSLAPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSLAPoliciesRow
	for rows.Next() {
		var i ListActiveSLAPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriorityOrder,
			&i.MatchConditions,
			&i.BusinessHoursID,
			&i.HolidayCalendarID,
			&i.ApplyTo,
			&i.TargetsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFirstResponseBreached = `-- name: MarkFirstResponseBreached :exec
UPDATE tickets SET first_response_breached = TRUE, updated_at = (now() AT TIME ZONE 'utc') WHERE id = $1
`

func (q *Queries) MarkFirstResponseBreached(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFirstResponseBreached, id)
	return err
}

const markResolutionBreached = `-- name: MarkResolutionBreached :exec
UPDATE tickets SET resolution_breached = TRUE, updated_at = (now() AT TIME ZONE 'utc') WHERE id = $1
`

func (q *Queries) MarkResolutionBreached(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markResolutionBreached, id)
	return err
}

const scanBreachingFirstResponseTickets = `-- name: ScanBreachingFirstResponseTickets :many
SELECT id, reference_no, sla_policy_id, priority_id, first_response_due_at, assigned_agent_id, assigned_team_id
FROM tickets
WHERE first_response_due_at <= $1
  AND first_responded_at IS NULL
  AND sla_paused_at IS NULL
  AND first_response_breached = FALSE
  AND deleted_at IS NULL
LIMIT $2
`

type ScanBreachingFirstResponseTicketsParams struct {
	FirstResponseDueAt pgtype.Timestamptz `json:"first_response_due_at"`
	Limit              int32              `json:"limit"`
}

type ScanBreachingFirstResponseTicketsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ReferenceNo        string             `json:"reference_no"`
	SlaPolicyID        pgtype.UUID        `json:"sla_policy_id"`
	PriorityID         pgtype.UUID        `json:"priority_id"`
	FirstResponseDueAt pgtype.Timestamptz `json:"first_response_due_at"`
	AssignedAgentID    pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID     pgtype.UUID        `json:"assigned_team_id"`
}

// Uses the partial index: tickets(first_response_due_at) WHERE first_responded_at IS NULL AND sla_paused_at IS NULL AND deleted_at IS NULL
func (q *Queries) ScanBreachingFirstResponseTickets(ctx context.Context, arg ScanBreachingFirstResponseTicketsParams) ([]ScanBreachingFirstResponseTicketsRow, error) {
	rows, err := q.db.Query(ctx, scanBreachingFirstResponseTickets, arg.FirstResponseDueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanBreachingFirstResponseTicketsRow
	for rows.Next() {
		var i ScanBreachingFirstResponseTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNo,
			&i.SlaPolicyID,
			&i.PriorityID,
			&i.FirstResponseDueAt,
			&i.AssignedAgentID,
			&i.AssignedTeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanBreachingResolutionTickets = `-- name: ScanBreachingResolutionTickets :many
SELECT id, reference_no, sla_policy_id, priority_id, resolution_due_at, assigned_agent_id, assigned_team_id
FROM tickets
WHERE resolution_due_at <= $1
  AND resolved_at IS NULL
  AND sla_paused_at IS NULL
  AND resolution_breached = FALSE
  AND deleted_at IS NULL
LIMIT $2
`

type ScanBreachingResolutionTicketsParams struct {
	ResolutionDueAt pgtype.Timestamptz `json:"resolution_due_at"`
	Limit           int32              `json:"limit"`
}

type ScanBreachingResolutionTicketsRow struct {
	ID              pgtype.UUID        `json:"id"`
	ReferenceNo     string             `json:"reference_no"`
	SlaPolicyID     pgtype.UUID        `json:"sla_policy_id"`
	PriorityID      pgtype.UUID        `json:"priority_id"`
	ResolutionDueAt pgtype.Timestamptz `json:"resolution_due_at"`
	AssignedAgentID pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID  pgtype.UUID        `json:"assigned_team_id"`
}

// Uses the partial index: tickets(resolution_due_at) WHERE resolved_at IS NULL AND sla_paused_at IS NULL AND deleted_at IS NULL
func (q *Queries) ScanBreachingResolutionTickets(ctx context.Context, arg ScanBreachingResolutionTicketsParams) ([]ScanBreachingResolutionTicketsRow, error) {
	rows, err := q.db.Query(ctx, scanBreachingResolutionTickets, arg.ResolutionDueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanBreachingResolutionTicketsRow
	for rows.Next() {
		var i ScanBreachingResolutionTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNo,
			&i.SlaPolicyID,
			&i.PriorityID,
			&i.ResolutionDueAt,
			&i.AssignedAgentID,
			&i.AssignedTeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
