// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTicketTag = `-- name: AddTicketTag :exec
INSERT INTO ticket_tags (ticket_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTicketTagParams struct {
	TicketID pgtype.UUID `json:"ticket_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTicketTag(ctx context.Context, arg AddTicketTagParams) error {
	_, err := q.db.Exec(ctx, addTicketTag, arg.TicketID, arg.TagID)
	return err
}

const addTicketWatcher = `-- name: AddTicketWatcher :exec
INSERT INTO ticket_watchers (ticket_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTicketWatcherParams struct {
	TicketID pgtype.UUID `json:"ticket_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddTicketWatcher(ctx context.Context, arg AddTicketWatcherParams) error {
	_, err := q.db.Exec(ctx, addTicketWatcher, arg.TicketID, arg.UserID)
	return err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    id,
    reference_no,
    subject,
    description_html,
    description_text,
    status_id,
    status_category,
    priority_id,
    priority_weight,
    type_id,
    contact_id,
    organization_id,
    assigned_agent_id,
    assigned_team_id,
    source,
    sla_policy_id,
    first_response_due_at,
    resolution_due_at,
    custom_data,
    created_by
) VALUES (
    $1,
    'TCK-' || nextval('ticket_reference_seq')::text,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19
) RETURNING 
    id, reference_no, subject, description_html, description_text, status_id, status_category,
    priority_id, priority_weight, type_id, contact_id, organization_id, assigned_agent_id, assigned_team_id,
    source, sla_policy_id, first_response_due_at, first_responded_at, resolution_due_at, resolved_at, closed_at,
    sla_paused_at, sla_paused_ms, first_response_breached, resolution_breached, reopen_count, merged_into_id,
    parent_ticket_id, last_customer_activity_at, last_agent_activity_at, feedback_rating, feedback_comment,
    custom_data, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateTicketParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Subject            string             `json:"subject"`
	DescriptionHtml    string             `json:"description_html"`
	DescriptionText    string             `json:"description_text"`
	StatusID           pgtype.UUID        `json:"status_id"`
	StatusCategory     string             `json:"status_category"`
	PriorityID         pgtype.UUID        `json:"priority_id"`
	PriorityWeight     int32              `json:"priority_weight"`
	TypeID             pgtype.UUID        `json:"type_id"`
	ContactID          pgtype.UUID        `json:"contact_id"`
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	AssignedAgentID    pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID     pgtype.UUID        `json:"assigned_team_id"`
	Source             string             `json:"source"`
	SlaPolicyID        pgtype.UUID        `json:"sla_policy_id"`
	FirstResponseDueAt pgtype.Timestamptz `json:"first_response_due_at"`
	ResolutionDueAt    pgtype.Timestamptz `json:"resolution_due_at"`
	CustomData         []byte             `json:"custom_data"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
}

type CreateTicketRow struct {
	ID                     pgtype.UUID        `json:"id"`
	ReferenceNo            string             `json:"reference_no"`
	Subject                string             `json:"subject"`
	DescriptionHtml        string             `json:"description_html"`
	DescriptionText        string             `json:"description_text"`
	StatusID               pgtype.UUID        `json:"status_id"`
	StatusCategory         string             `json:"status_category"`
	PriorityID             pgtype.UUID        `json:"priority_id"`
	PriorityWeight         int32              `json:"priority_weight"`
	TypeID                 pgtype.UUID        `json:"type_id"`
	ContactID              pgtype.UUID        `json:"contact_id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	AssignedAgentID        pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID         pgtype.UUID        `json:"assigned_team_id"`
	Source                 string             `json:"source"`
	SlaPolicyID            pgtype.UUID        `json:"sla_policy_id"`
	FirstResponseDueAt     pgtype.Timestamptz `json:"first_response_due_at"`
	FirstRespondedAt       pgtype.Timestamptz `json:"first_responded_at"`
	ResolutionDueAt        pgtype.Timestamptz `json:"resolution_due_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	SlaPausedAt            pgtype.Timestamptz `json:"sla_paused_at"`
	SlaPausedMs            int64              `json:"sla_paused_ms"`
	FirstResponseBreached  bool               `json:"first_response_breached"`
	ResolutionBreached     bool               `json:"resolution_breached"`
	ReopenCount            int32              `json:"reopen_count"`
	MergedIntoID           pgtype.UUID        `json:"merged_into_id"`
	ParentTicketID         pgtype.UUID        `json:"parent_ticket_id"`
	LastCustomerActivityAt pgtype.Timestamptz `json:"last_customer_activity_at"`
	LastAgentActivityAt    pgtype.Timestamptz `json:"last_agent_activity_at"`
	FeedbackRating         pgtype.Int4        `json:"feedback_rating"`
	FeedbackComment        pgtype.Text        `json:"feedback_comment"`
	CustomData             []byte             `json:"custom_data"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (CreateTicketRow, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ID,
		arg.Subject,
		arg.DescriptionHtml,
		arg.DescriptionText,
		arg.StatusID,
		arg.StatusCategory,
		arg.PriorityID,
		arg.PriorityWeight,
		arg.TypeID,
		arg.ContactID,
		arg.OrganizationID,
		arg.AssignedAgentID,
		arg.AssignedTeamID,
		arg.Source,
		arg.SlaPolicyID,
		arg.FirstResponseDueAt,
		arg.ResolutionDueAt,
		arg.CustomData,
		arg.CreatedBy,
	)
	var i CreateTicketRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.Subject,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.StatusID,
		&i.StatusCategory,
		&i.PriorityID,
		&i.PriorityWeight,
		&i.TypeID,
		&i.ContactID,
		&i.OrganizationID,
		&i.AssignedAgentID,
		&i.AssignedTeamID,
		&i.Source,
		&i.SlaPolicyID,
		&i.FirstResponseDueAt,
		&i.FirstRespondedAt,
		&i.ResolutionDueAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.SlaPausedAt,
		&i.SlaPausedMs,
		&i.FirstResponseBreached,
		&i.ResolutionBreached,
		&i.ReopenCount,
		&i.MergedIntoID,
		&i.ParentTicketID,
		&i.LastCustomerActivityAt,
		&i.LastAgentActivityAt,
		&i.FeedbackRating,
		&i.FeedbackComment,
		&i.CustomData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketByReferenceNo = `-- name: GetTicketByReferenceNo :one
SELECT 
    id, reference_no, subject, description_html, description_text, status_id, status_category,
    priority_id, priority_weight, type_id, contact_id, organization_id, assigned_agent_id, assigned_team_id,
    source, sla_policy_id, first_response_due_at, first_responded_at, resolution_due_at, resolved_at, closed_at,
    sla_paused_at, sla_paused_ms, first_response_breached, resolution_breached, reopen_count, merged_into_id,
    parent_ticket_id, last_customer_activity_at, last_agent_activity_at, feedback_rating, feedback_comment,
    custom_data, created_at, updated_at, created_by, updated_by, deleted_at
FROM tickets WHERE reference_no = $1 AND deleted_at IS NULL
`

type GetTicketByReferenceNoRow struct {
	ID                     pgtype.UUID        `json:"id"`
	ReferenceNo            string             `json:"reference_no"`
	Subject                string             `json:"subject"`
	DescriptionHtml        string             `json:"description_html"`
	DescriptionText        string             `json:"description_text"`
	StatusID               pgtype.UUID        `json:"status_id"`
	StatusCategory         string             `json:"status_category"`
	PriorityID             pgtype.UUID        `json:"priority_id"`
	PriorityWeight         int32              `json:"priority_weight"`
	TypeID                 pgtype.UUID        `json:"type_id"`
	ContactID              pgtype.UUID        `json:"contact_id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	AssignedAgentID        pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID         pgtype.UUID        `json:"assigned_team_id"`
	Source                 string             `json:"source"`
	SlaPolicyID            pgtype.UUID        `json:"sla_policy_id"`
	FirstResponseDueAt     pgtype.Timestamptz `json:"first_response_due_at"`
	FirstRespondedAt       pgtype.Timestamptz `json:"first_responded_at"`
	ResolutionDueAt        pgtype.Timestamptz `json:"resolution_due_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	SlaPausedAt            pgtype.Timestamptz `json:"sla_paused_at"`
	SlaPausedMs            int64              `json:"sla_paused_ms"`
	FirstResponseBreached  bool               `json:"first_response_breached"`
	ResolutionBreached     bool               `json:"resolution_breached"`
	ReopenCount            int32              `json:"reopen_count"`
	MergedIntoID           pgtype.UUID        `json:"merged_into_id"`
	ParentTicketID         pgtype.UUID        `json:"parent_ticket_id"`
	LastCustomerActivityAt pgtype.Timestamptz `json:"last_customer_activity_at"`
	LastAgentActivityAt    pgtype.Timestamptz `json:"last_agent_activity_at"`
	FeedbackRating         pgtype.Int4        `json:"feedback_rating"`
	FeedbackComment        pgtype.Text        `json:"feedback_comment"`
	CustomData             []byte             `json:"custom_data"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetTicketByReferenceNo(ctx context.Context, referenceNo string) (GetTicketByReferenceNoRow, error) {
	row := q.db.QueryRow(ctx, getTicketByReferenceNo, referenceNo)
	var i GetTicketByReferenceNoRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.Subject,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.StatusID,
		&i.StatusCategory,
		&i.PriorityID,
		&i.PriorityWeight,
		&i.TypeID,
		&i.ContactID,
		&i.OrganizationID,
		&i.AssignedAgentID,
		&i.AssignedTeamID,
		&i.Source,
		&i.SlaPolicyID,
		&i.FirstResponseDueAt,
		&i.FirstRespondedAt,
		&i.ResolutionDueAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.SlaPausedAt,
		&i.SlaPausedMs,
		&i.FirstResponseBreached,
		&i.ResolutionBreached,
		&i.ReopenCount,
		&i.MergedIntoID,
		&i.ParentTicketID,
		&i.LastCustomerActivityAt,
		&i.LastAgentActivityAt,
		&i.FeedbackRating,
		&i.FeedbackComment,
		&i.CustomData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketDetail = `-- name: GetTicketDetail :one
SELECT 
    t.id,
    t.reference_no,
    t.subject,
    t.description_html,
    t.description_text,
    t.status_id,
    ts.key AS status_key,
    ts.label AS status_label,
    ts.category AS status_category,
    ts.pauses_sla,
    ts.stops_sla,
    t.priority_id,
    tp.key AS priority_key,
    tp.label AS priority_label,
    t.priority_weight,
    t.type_id,
    tt.key AS type_key,
    tt.label AS type_label,
    t.contact_id,
    c.full_name AS contact_name,
    c.primary_email AS contact_email,
    c.phone AS contact_phone,
    c.locale AS contact_locale,
    t.organization_id,
    org.name AS organization_name,
    org.domain AS organization_domain,
    t.assigned_agent_id,
    ag.display_name AS assigned_agent_name,
    ag.user_id AS assigned_agent_user_id,
    t.assigned_team_id,
    tm.name AS assigned_team_name,
    t.source,
    t.sla_policy_id,
    sp.name AS sla_policy_name,
    t.first_response_due_at,
    t.first_responded_at,
    t.resolution_due_at,
    t.resolved_at,
    t.closed_at,
    t.sla_paused_at,
    t.sla_paused_ms,
    t.first_response_breached,
    t.resolution_breached,
    t.reopen_count,
    t.merged_into_id,
    t.parent_ticket_id,
    t.last_customer_activity_at,
    t.last_agent_activity_at,
    t.feedback_rating,
    t.feedback_comment,
    t.custom_data,
    t.created_at,
    t.updated_at,
    COALESCE(
        (SELECT json_agg(json_build_object('id', tg.id, 'key', tg.key, 'label', tg.label))
         FROM ticket_tags tt_tag
         JOIN tags tg ON tg.id = tt_tag.tag_id
         WHERE tt_tag.ticket_id = t.id),
        '[]'::json
    ) AS tags_json,
    COALESCE(
        (SELECT json_agg(json_build_object('id', u.id, 'name', u.full_name, 'email', u.email))
         FROM ticket_watchers tw
         JOIN users u ON u.id = tw.user_id
         WHERE tw.ticket_id = t.id),
        '[]'::json
    ) AS watchers_json,
    COALESCE(
        (SELECT json_agg(json_build_object('from_ticket_id', tl.from_ticket_id, 'to_ticket_id', tl.to_ticket_id, 'relation', tl.relation, 'to_reference_no', t2.reference_no, 'to_subject', t2.subject))
         FROM ticket_links tl
         JOIN tickets t2 ON t2.id = tl.to_ticket_id
         WHERE tl.from_ticket_id = t.id),
        '[]'::json
    ) AS links_json
FROM tickets t
JOIN ticket_statuses ts ON ts.id = t.status_id
JOIN ticket_priorities tp ON tp.id = t.priority_id
LEFT JOIN ticket_types tt ON tt.id = t.type_id
JOIN contacts c ON c.id = t.contact_id
LEFT JOIN organizations org ON org.id = t.organization_id
LEFT JOIN agents ag ON ag.id = t.assigned_agent_id
LEFT JOIN teams tm ON tm.id = t.assigned_team_id
LEFT JOIN sla_policies sp ON sp.id = t.sla_policy_id
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTicketDetailRow struct {
	ID                     pgtype.UUID        `json:"id"`
	ReferenceNo            string             `json:"reference_no"`
	Subject                string             `json:"subject"`
	DescriptionHtml        string             `json:"description_html"`
	DescriptionText        string             `json:"description_text"`
	StatusID               pgtype.UUID        `json:"status_id"`
	StatusKey              string             `json:"status_key"`
	StatusLabel            string             `json:"status_label"`
	StatusCategory         string             `json:"status_category"`
	PausesSla              bool               `json:"pauses_sla"`
	StopsSla               bool               `json:"stops_sla"`
	PriorityID             pgtype.UUID        `json:"priority_id"`
	PriorityKey            string             `json:"priority_key"`
	PriorityLabel          string             `json:"priority_label"`
	PriorityWeight         int32              `json:"priority_weight"`
	TypeID                 pgtype.UUID        `json:"type_id"`
	TypeKey                pgtype.Text        `json:"type_key"`
	TypeLabel              pgtype.Text        `json:"type_label"`
	ContactID              pgtype.UUID        `json:"contact_id"`
	ContactName            string             `json:"contact_name"`
	ContactEmail           string             `json:"contact_email"`
	ContactPhone           pgtype.Text        `json:"contact_phone"`
	ContactLocale          string             `json:"contact_locale"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	OrganizationName       pgtype.Text        `json:"organization_name"`
	OrganizationDomain     pgtype.Text        `json:"organization_domain"`
	AssignedAgentID        pgtype.UUID        `json:"assigned_agent_id"`
	AssignedAgentName      pgtype.Text        `json:"assigned_agent_name"`
	AssignedAgentUserID    pgtype.UUID        `json:"assigned_agent_user_id"`
	AssignedTeamID         pgtype.UUID        `json:"assigned_team_id"`
	AssignedTeamName       pgtype.Text        `json:"assigned_team_name"`
	Source                 string             `json:"source"`
	SlaPolicyID            pgtype.UUID        `json:"sla_policy_id"`
	SlaPolicyName          pgtype.Text        `json:"sla_policy_name"`
	FirstResponseDueAt     pgtype.Timestamptz `json:"first_response_due_at"`
	FirstRespondedAt       pgtype.Timestamptz `json:"first_responded_at"`
	ResolutionDueAt        pgtype.Timestamptz `json:"resolution_due_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	SlaPausedAt            pgtype.Timestamptz `json:"sla_paused_at"`
	SlaPausedMs            int64              `json:"sla_paused_ms"`
	FirstResponseBreached  bool               `json:"first_response_breached"`
	ResolutionBreached     bool               `json:"resolution_breached"`
	ReopenCount            int32              `json:"reopen_count"`
	MergedIntoID           pgtype.UUID        `json:"merged_into_id"`
	ParentTicketID         pgtype.UUID        `json:"parent_ticket_id"`
	LastCustomerActivityAt pgtype.Timestamptz `json:"last_customer_activity_at"`
	LastAgentActivityAt    pgtype.Timestamptz `json:"last_agent_activity_at"`
	FeedbackRating         pgtype.Int4        `json:"feedback_rating"`
	FeedbackComment        pgtype.Text        `json:"feedback_comment"`
	CustomData             []byte             `json:"custom_data"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	TagsJson               interface{}        `json:"tags_json"`
	WatchersJson           interface{}        `json:"watchers_json"`
	LinksJson              interface{}        `json:"links_json"`
}

// Query 1 of 2 for Ticket Detail: Full Ticket metadata with associations
func (q *Queries) GetTicketDetail(ctx context.Context, id pgtype.UUID) (GetTicketDetailRow, error) {
	row := q.db.QueryRow(ctx, getTicketDetail, id)
	var i GetTicketDetailRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.Subject,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.StatusID,
		&i.StatusKey,
		&i.StatusLabel,
		&i.StatusCategory,
		&i.PausesSla,
		&i.StopsSla,
		&i.PriorityID,
		&i.PriorityKey,
		&i.PriorityLabel,
		&i.PriorityWeight,
		&i.TypeID,
		&i.TypeKey,
		&i.TypeLabel,
		&i.ContactID,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.ContactLocale,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.OrganizationDomain,
		&i.AssignedAgentID,
		&i.AssignedAgentName,
		&i.AssignedAgentUserID,
		&i.AssignedTeamID,
		&i.AssignedTeamName,
		&i.Source,
		&i.SlaPolicyID,
		&i.SlaPolicyName,
		&i.FirstResponseDueAt,
		&i.FirstRespondedAt,
		&i.ResolutionDueAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.SlaPausedAt,
		&i.SlaPausedMs,
		&i.FirstResponseBreached,
		&i.ResolutionBreached,
		&i.ReopenCount,
		&i.MergedIntoID,
		&i.ParentTicketID,
		&i.LastCustomerActivityAt,
		&i.LastAgentActivityAt,
		&i.FeedbackRating,
		&i.FeedbackComment,
		&i.CustomData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TagsJson,
		&i.WatchersJson,
		&i.LinksJson,
	)
	return i, err
}

const linkTickets = `-- name: LinkTickets :exec
INSERT INTO ticket_links (from_ticket_id, to_ticket_id, relation) 
VALUES ($1, $2, $3) 
ON CONFLICT (from_ticket_id, to_ticket_id, relation) DO NOTHING
`

type LinkTicketsParams struct {
	FromTicketID pgtype.UUID `json:"from_ticket_id"`
	ToTicketID   pgtype.UUID `json:"to_ticket_id"`
	Relation     string      `json:"relation"`
}

func (q *Queries) LinkTickets(ctx context.Context, arg LinkTicketsParams) error {
	_, err := q.db.Exec(ctx, linkTickets, arg.FromTicketID, arg.ToTicketID, arg.Relation)
	return err
}

const listTicketsKeyset = `-- name: ListTicketsKeyset :many
SELECT 
    t.id,
    t.reference_no,
    t.subject,
    t.description_text,
    t.status_id,
    ts.key AS status_key,
    ts.label AS status_label,
    t.status_category,
    t.priority_id,
    tp.key AS priority_key,
    tp.label AS priority_label,
    t.priority_weight,
    t.type_id,
    tt.key AS type_key,
    tt.label AS type_label,
    t.contact_id,
    c.full_name AS contact_name,
    c.primary_email AS contact_email,
    t.organization_id,
    org.name AS organization_name,
    t.assigned_agent_id,
    ag.display_name AS assigned_agent_name,
    t.assigned_team_id,
    tm.name AS assigned_team_name,
    t.source,
    t.first_response_due_at,
    t.first_responded_at,
    t.resolution_due_at,
    t.resolved_at,
    t.closed_at,
    t.first_response_breached,
    t.resolution_breached,
    t.reopen_count,
    t.last_customer_activity_at,
    t.last_agent_activity_at,
    t.custom_data,
    t.created_at,
    t.updated_at,
    COALESCE(
        (SELECT json_agg(json_build_object('id', tg.id, 'key', tg.key, 'label', tg.label))
         FROM ticket_tags tt_tag
         JOIN tags tg ON tg.id = tt_tag.tag_id
         WHERE tt_tag.ticket_id = t.id),
        '[]'::json
    ) AS tags_json
FROM tickets t
JOIN ticket_statuses ts ON ts.id = t.status_id
JOIN ticket_priorities tp ON tp.id = t.priority_id
LEFT JOIN ticket_types tt ON tt.id = t.type_id
JOIN contacts c ON c.id = t.contact_id
LEFT JOIN organizations org ON org.id = t.organization_id
LEFT JOIN agents ag ON ag.id = t.assigned_agent_id
LEFT JOIN teams tm ON tm.id = t.assigned_team_id
WHERE t.deleted_at IS NULL
  AND (
    $2::text IS NULL 
    OR ($2::text = 'resolved' AND t.status_category IN ('resolved', 'closed'))
    OR ($2::text = 'open' AND t.status_category IN ('open', 'new'))
    OR ($2::text = 'pending' AND t.status_category IN ('pending', 'paused'))
    OR t.status_category = $2
  )
  AND ($3::uuid IS NULL OR t.assigned_agent_id = $3)
  AND ($4::uuid IS NULL OR t.assigned_team_id = $4)
  AND ($5::uuid IS NULL OR t.contact_id = $5)
  AND ($6::text IS NULL OR t.search_vector @@ websearch_to_tsquery('english', $6))
  AND (
    $7::timestamptz IS NULL 
    OR (t.updated_at, t.id) < ($7, $8::uuid)
  )
ORDER BY t.updated_at DESC, t.id DESC
LIMIT $1
`

type ListTicketsKeysetParams struct {
	Limit           int32              `json:"limit"`
	StatusCategory  pgtype.Text        `json:"status_category"`
	AssignedAgentID pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID  pgtype.UUID        `json:"assigned_team_id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	SearchQuery     pgtype.Text        `json:"search_query"`
	AfterUpdatedAt  pgtype.Timestamptz `json:"after_updated_at"`
	AfterID         pgtype.UUID        `json:"after_id"`
}

type ListTicketsKeysetRow struct {
	ID                     pgtype.UUID        `json:"id"`
	ReferenceNo            string             `json:"reference_no"`
	Subject                string             `json:"subject"`
	DescriptionText        string             `json:"description_text"`
	StatusID               pgtype.UUID        `json:"status_id"`
	StatusKey              string             `json:"status_key"`
	StatusLabel            string             `json:"status_label"`
	StatusCategory         string             `json:"status_category"`
	PriorityID             pgtype.UUID        `json:"priority_id"`
	PriorityKey            string             `json:"priority_key"`
	PriorityLabel          string             `json:"priority_label"`
	PriorityWeight         int32              `json:"priority_weight"`
	TypeID                 pgtype.UUID        `json:"type_id"`
	TypeKey                pgtype.Text        `json:"type_key"`
	TypeLabel              pgtype.Text        `json:"type_label"`
	ContactID              pgtype.UUID        `json:"contact_id"`
	ContactName            string             `json:"contact_name"`
	ContactEmail           string             `json:"contact_email"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	OrganizationName       pgtype.Text        `json:"organization_name"`
	AssignedAgentID        pgtype.UUID        `json:"assigned_agent_id"`
	AssignedAgentName      pgtype.Text        `json:"assigned_agent_name"`
	AssignedTeamID         pgtype.UUID        `json:"assigned_team_id"`
	AssignedTeamName       pgtype.Text        `json:"assigned_team_name"`
	Source                 string             `json:"source"`
	FirstResponseDueAt     pgtype.Timestamptz `json:"first_response_due_at"`
	FirstRespondedAt       pgtype.Timestamptz `json:"first_responded_at"`
	ResolutionDueAt        pgtype.Timestamptz `json:"resolution_due_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	FirstResponseBreached  bool               `json:"first_response_breached"`
	ResolutionBreached     bool               `json:"resolution_breached"`
	ReopenCount            int32              `json:"reopen_count"`
	LastCustomerActivityAt pgtype.Timestamptz `json:"last_customer_activity_at"`
	LastAgentActivityAt    pgtype.Timestamptz `json:"last_agent_activity_at"`
	CustomData             []byte             `json:"custom_data"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	TagsJson               interface{}        `json:"tags_json"`
}

// 1 Query Ticket List with Keyset Pagination and complete aggregated details
func (q *Queries) ListTicketsKeyset(ctx context.Context, arg ListTicketsKeysetParams) ([]ListTicketsKeysetRow, error) {
	rows, err := q.db.Query(ctx, listTicketsKeyset,
		arg.Limit,
		arg.StatusCategory,
		arg.AssignedAgentID,
		arg.AssignedTeamID,
		arg.ContactID,
		arg.SearchQuery,
		arg.AfterUpdatedAt,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsKeysetRow
	for rows.Next() {
		var i ListTicketsKeysetRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNo,
			&i.Subject,
			&i.DescriptionText,
			&i.StatusID,
			&i.StatusKey,
			&i.StatusLabel,
			&i.StatusCategory,
			&i.PriorityID,
			&i.PriorityKey,
			&i.PriorityLabel,
			&i.PriorityWeight,
			&i.TypeID,
			&i.TypeKey,
			&i.TypeLabel,
			&i.ContactID,
			&i.ContactName,
			&i.ContactEmail,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.AssignedAgentID,
			&i.AssignedAgentName,
			&i.AssignedTeamID,
			&i.AssignedTeamName,
			&i.Source,
			&i.FirstResponseDueAt,
			&i.FirstRespondedAt,
			&i.ResolutionDueAt,
			&i.ResolvedAt,
			&i.ClosedAt,
			&i.FirstResponseBreached,
			&i.ResolutionBreached,
			&i.ReopenCount,
			&i.LastCustomerActivityAt,
			&i.LastAgentActivityAt,
			&i.CustomData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TagsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTicketTag = `-- name: RemoveTicketTag :exec
DELETE FROM ticket_tags WHERE ticket_id = $1 AND tag_id = $2
`

type RemoveTicketTagParams struct {
	TicketID pgtype.UUID `json:"ticket_id"`
	TagID    pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTicketTag(ctx context.Context, arg RemoveTicketTagParams) error {
	_, err := q.db.Exec(ctx, removeTicketTag, arg.TicketID, arg.TagID)
	return err
}

const removeTicketWatcher = `-- name: RemoveTicketWatcher :exec
DELETE FROM ticket_watchers WHERE ticket_id = $1 AND user_id = $2
`

type RemoveTicketWatcherParams struct {
	TicketID pgtype.UUID `json:"ticket_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTicketWatcher(ctx context.Context, arg RemoveTicketWatcherParams) error {
	_, err := q.db.Exec(ctx, removeTicketWatcher, arg.TicketID, arg.UserID)
	return err
}

const softDeleteTicket = `-- name: SoftDeleteTicket :exec
UPDATE tickets 
SET deleted_at = (now() AT TIME ZONE 'utc'), updated_by = $2
WHERE id = $1
`

type SoftDeleteTicketParams struct {
	ID        pgtype.UUID `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteTicket(ctx context.Context, arg SoftDeleteTicketParams) error {
	_, err := q.db.Exec(ctx, softDeleteTicket, arg.ID, arg.UpdatedBy)
	return err
}

const unlinkTickets = `-- name: UnlinkTickets :exec
DELETE FROM ticket_links WHERE from_ticket_id = $1 AND to_ticket_id = $2 AND relation = $3
`

type UnlinkTicketsParams struct {
	FromTicketID pgtype.UUID `json:"from_ticket_id"`
	ToTicketID   pgtype.UUID `json:"to_ticket_id"`
	Relation     string      `json:"relation"`
}

func (q *Queries) UnlinkTickets(ctx context.Context, arg UnlinkTicketsParams) error {
	_, err := q.db.Exec(ctx, unlinkTickets, arg.FromTicketID, arg.ToTicketID, arg.Relation)
	return err
}

const updateTicketFields = `-- name: UpdateTicketFields :one
UPDATE tickets
SET 
    subject = COALESCE($2, subject),
    description_html = COALESCE($3, description_html),
    description_text = COALESCE($4, description_text),
    status_id = COALESCE($5, status_id),
    status_category = COALESCE($6, status_category),
    priority_id = COALESCE($7, priority_id),
    priority_weight = COALESCE($8, priority_weight),
    type_id = COALESCE($9, type_id),
    assigned_agent_id = $10,
    assigned_team_id = $11,
    sla_policy_id = COALESCE($12, sla_policy_id),
    first_response_due_at = $13,
    first_responded_at = COALESCE($14, first_responded_at),
    resolution_due_at = $15,
    resolved_at = $16,
    closed_at = $17,
    sla_paused_at = $18,
    sla_paused_ms = COALESCE($19, sla_paused_ms),
    first_response_breached = COALESCE($20, first_response_breached),
    resolution_breached = COALESCE($21, resolution_breached),
    reopen_count = COALESCE($22, reopen_count),
    last_customer_activity_at = COALESCE($23, last_customer_activity_at),
    last_agent_activity_at = COALESCE($24, last_agent_activity_at),
    feedback_rating = COALESCE($25, feedback_rating),
    feedback_comment = COALESCE($26, feedback_comment),
    custom_data = COALESCE($27, custom_data),
    updated_at = (now() AT TIME ZONE 'utc'),
    updated_by = $28
WHERE id = $1 AND deleted_at IS NULL
RETURNING 
    id, reference_no, subject, description_html, description_text, status_id, status_category,
    priority_id, priority_weight, type_id, contact_id, organization_id, assigned_agent_id, assigned_team_id,
    source, sla_policy_id, first_response_due_at, first_responded_at, resolution_due_at, resolved_at, closed_at,
    sla_paused_at, sla_paused_ms, first_response_breached, resolution_breached, reopen_count, merged_into_id,
    parent_ticket_id, last_customer_activity_at, last_agent_activity_at, feedback_rating, feedback_comment,
    custom_data, created_at, updated_at, created_by, updated_by, deleted_at
`

type UpdateTicketFieldsParams struct {
	ID                     pgtype.UUID        `json:"id"`
	Subject                pgtype.Text        `json:"subject"`
	DescriptionHtml        pgtype.Text        `json:"description_html"`
	DescriptionText        pgtype.Text        `json:"description_text"`
	StatusID               pgtype.UUID        `json:"status_id"`
	StatusCategory         pgtype.Text        `json:"status_category"`
	PriorityID             pgtype.UUID        `json:"priority_id"`
	PriorityWeight         pgtype.Int4        `json:"priority_weight"`
	TypeID                 pgtype.UUID        `json:"type_id"`
	AssignedAgentID        pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID         pgtype.UUID        `json:"assigned_team_id"`
	SlaPolicyID            pgtype.UUID        `json:"sla_policy_id"`
	FirstResponseDueAt     pgtype.Timestamptz `json:"first_response_due_at"`
	FirstRespondedAt       pgtype.Timestamptz `json:"first_responded_at"`
	ResolutionDueAt        pgtype.Timestamptz `json:"resolution_due_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	SlaPausedAt            pgtype.Timestamptz `json:"sla_paused_at"`
	SlaPausedMs            pgtype.Int8        `json:"sla_paused_ms"`
	FirstResponseBreached  pgtype.Bool        `json:"first_response_breached"`
	ResolutionBreached     pgtype.Bool        `json:"resolution_breached"`
	ReopenCount            pgtype.Int4        `json:"reopen_count"`
	LastCustomerActivityAt pgtype.Timestamptz `json:"last_customer_activity_at"`
	LastAgentActivityAt    pgtype.Timestamptz `json:"last_agent_activity_at"`
	FeedbackRating         pgtype.Int4        `json:"feedback_rating"`
	FeedbackComment        pgtype.Text        `json:"feedback_comment"`
	CustomData             []byte             `json:"custom_data"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
}

type UpdateTicketFieldsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	ReferenceNo            string             `json:"reference_no"`
	Subject                string             `json:"subject"`
	DescriptionHtml        string             `json:"description_html"`
	DescriptionText        string             `json:"description_text"`
	StatusID               pgtype.UUID        `json:"status_id"`
	StatusCategory         string             `json:"status_category"`
	PriorityID             pgtype.UUID        `json:"priority_id"`
	PriorityWeight         int32              `json:"priority_weight"`
	TypeID                 pgtype.UUID        `json:"type_id"`
	ContactID              pgtype.UUID        `json:"contact_id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	AssignedAgentID        pgtype.UUID        `json:"assigned_agent_id"`
	AssignedTeamID         pgtype.UUID        `json:"assigned_team_id"`
	Source                 string             `json:"source"`
	SlaPolicyID            pgtype.UUID        `json:"sla_policy_id"`
	FirstResponseDueAt     pgtype.Timestamptz `json:"first_response_due_at"`
	FirstRespondedAt       pgtype.Timestamptz `json:"first_responded_at"`
	ResolutionDueAt        pgtype.Timestamptz `json:"resolution_due_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	SlaPausedAt            pgtype.Timestamptz `json:"sla_paused_at"`
	SlaPausedMs            int64              `json:"sla_paused_ms"`
	FirstResponseBreached  bool               `json:"first_response_breached"`
	ResolutionBreached     bool               `json:"resolution_breached"`
	ReopenCount            int32              `json:"reopen_count"`
	MergedIntoID           pgtype.UUID        `json:"merged_into_id"`
	ParentTicketID         pgtype.UUID        `json:"parent_ticket_id"`
	LastCustomerActivityAt pgtype.Timestamptz `json:"last_customer_activity_at"`
	LastAgentActivityAt    pgtype.Timestamptz `json:"last_agent_activity_at"`
	FeedbackRating         pgtype.Int4        `json:"feedback_rating"`
	FeedbackComment        pgtype.Text        `json:"feedback_comment"`
	CustomData             []byte             `json:"custom_data"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateTicketFields(ctx context.Context, arg UpdateTicketFieldsParams) (UpdateTicketFieldsRow, error) {
	row := q.db.QueryRow(ctx, updateTicketFields,
		arg.ID,
		arg.Subject,
		arg.DescriptionHtml,
		arg.DescriptionText,
		arg.StatusID,
		arg.StatusCategory,
		arg.PriorityID,
		arg.PriorityWeight,
		arg.TypeID,
		arg.AssignedAgentID,
		arg.AssignedTeamID,
		arg.SlaPolicyID,
		arg.FirstResponseDueAt,
		arg.FirstRespondedAt,
		arg.ResolutionDueAt,
		arg.ResolvedAt,
		arg.ClosedAt,
		arg.SlaPausedAt,
		arg.SlaPausedMs,
		arg.FirstResponseBreached,
		arg.ResolutionBreached,
		arg.ReopenCount,
		arg.LastCustomerActivityAt,
		arg.LastAgentActivityAt,
		arg.FeedbackRating,
		arg.FeedbackComment,
		arg.CustomData,
		arg.UpdatedBy,
	)
	var i UpdateTicketFieldsRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.Subject,
		&i.DescriptionHtml,
		&i.DescriptionText,
		&i.StatusID,
		&i.StatusCategory,
		&i.PriorityID,
		&i.PriorityWeight,
		&i.TypeID,
		&i.ContactID,
		&i.OrganizationID,
		&i.AssignedAgentID,
		&i.AssignedTeamID,
		&i.Source,
		&i.SlaPolicyID,
		&i.FirstResponseDueAt,
		&i.FirstRespondedAt,
		&i.ResolutionDueAt,
		&i.ResolvedAt,
		&i.ClosedAt,
		&i.SlaPausedAt,
		&i.SlaPausedMs,
		&i.FirstResponseBreached,
		&i.ResolutionBreached,
		&i.ReopenCount,
		&i.MergedIntoID,
		&i.ParentTicketID,
		&i.LastCustomerActivityAt,
		&i.LastAgentActivityAt,
		&i.FeedbackRating,
		&i.FeedbackComment,
		&i.CustomData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
