// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    id,
    user_id,
    display_name,
    signature_html,
    is_available,
    max_concurrent_tickets,
    skills
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, display_name, signature_html, is_available, max_concurrent_tickets, skills, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateAgentParams struct {
	ID                   pgtype.UUID `json:"id"`
	UserID               pgtype.UUID `json:"user_id"`
	DisplayName          string      `json:"display_name"`
	SignatureHtml        string      `json:"signature_html"`
	IsAvailable          bool        `json:"is_available"`
	MaxConcurrentTickets int32       `json:"max_concurrent_tickets"`
	Skills               []string    `json:"skills"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agents, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.SignatureHtml,
		arg.IsAvailable,
		arg.MaxConcurrentTickets,
		arg.Skills,
	)
	var i Agents
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.SignatureHtml,
		&i.IsAvailable,
		&i.MaxConcurrentTickets,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    id,
    organization_id,
    primary_email,
    full_name,
    phone,
    locale,
    timezone,
    is_verified,
    portal_user_id,
    custom_data,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, organization_id, primary_email, full_name, phone, locale, timezone, is_verified, portal_user_id, custom_data, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateContactParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PrimaryEmail   string      `json:"primary_email"`
	FullName       string      `json:"full_name"`
	Phone          pgtype.Text `json:"phone"`
	Locale         string      `json:"locale"`
	Timezone       string      `json:"timezone"`
	IsVerified     bool        `json:"is_verified"`
	PortalUserID   pgtype.UUID `json:"portal_user_id"`
	CustomData     []byte      `json:"custom_data"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contacts, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ID,
		arg.OrganizationID,
		arg.PrimaryEmail,
		arg.FullName,
		arg.Phone,
		arg.Locale,
		arg.Timezone,
		arg.IsVerified,
		arg.PortalUserID,
		arg.CustomData,
		arg.CreatedBy,
	)
	var i Contacts
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PrimaryEmail,
		&i.FullName,
		&i.Phone,
		&i.Locale,
		&i.Timezone,
		&i.IsVerified,
		&i.PortalUserID,
		&i.CustomData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    full_name,
    timezone,
    locale,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email, password_hash, full_name, timezone, locale, is_active, last_login_at, mfa_secret, created_at, updated_at, created_by, updated_by, deleted_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Timezone     string      `json:"timezone"`
	Locale       string      `json:"locale"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Timezone,
		arg.Locale,
		arg.IsActive,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Timezone,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentByUserID = `-- name: GetAgentByUserID :one
SELECT id, user_id, display_name, signature_html, is_available, max_concurrent_tickets, skills, created_at, updated_at, created_by, updated_by, deleted_at FROM agents WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentByUserID(ctx context.Context, userID pgtype.UUID) (Agents, error) {
	row := q.db.QueryRow(ctx, getAgentByUserID, userID)
	var i Agents
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.SignatureHtml,
		&i.IsAvailable,
		&i.MaxConcurrentTickets,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getContactByEmail = `-- name: GetContactByEmail :one
SELECT id, organization_id, primary_email, full_name, phone, locale, timezone, is_verified, portal_user_id, custom_data, created_at, updated_at, created_by, updated_by, deleted_at FROM contacts WHERE primary_email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContactByEmail(ctx context.Context, primaryEmail string) (Contacts, error) {
	row := q.db.QueryRow(ctx, getContactByEmail, primaryEmail)
	var i Contacts
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PrimaryEmail,
		&i.FullName,
		&i.Phone,
		&i.Locale,
		&i.Timezone,
		&i.IsVerified,
		&i.PortalUserID,
		&i.CustomData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, organization_id, primary_email, full_name, phone, locale, timezone, is_verified, portal_user_id, custom_data, created_at, updated_at, created_by, updated_by, deleted_at FROM contacts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContactByID(ctx context.Context, id pgtype.UUID) (Contacts, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contacts
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PrimaryEmail,
		&i.FullName,
		&i.Phone,
		&i.Locale,
		&i.Timezone,
		&i.IsVerified,
		&i.PortalUserID,
		&i.CustomData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getOrCreateOrganizationByDomain = `-- name: GetOrCreateOrganizationByDomain :one
INSERT INTO organizations (
    id,
    name,
    slug,
    domain
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (slug) DO UPDATE SET updated_at = (now() AT TIME ZONE 'utc')
RETURNING id, name, slug, domain, default_timezone, settings, created_at, updated_at, created_by, updated_by, deleted_at
`

type GetOrCreateOrganizationByDomainParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Slug   string      `json:"slug"`
	Domain pgtype.Text `json:"domain"`
}

func (q *Queries) GetOrCreateOrganizationByDomain(ctx context.Context, arg GetOrCreateOrganizationByDomainParams) (Organizations, error) {
	row := q.db.QueryRow(ctx, getOrCreateOrganizationByDomain,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Domain,
	)
	var i Organizations
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.DefaultTimezone,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByKey = `-- name: GetRoleByKey :one
SELECT id, key, label, description, is_system, created_at, updated_at, created_by, updated_by, deleted_at FROM roles WHERE key = $1 LIMIT 1
`

func (q *Queries) GetRoleByKey(ctx context.Context, key string) (Roles, error) {
	row := q.db.QueryRow(ctx, getRoleByKey, key)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, timezone, locale, is_active, last_login_at, mfa_secret, created_at, updated_at, created_by, updated_by, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Timezone,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, timezone, locale, is_active, last_login_at, mfa_secret, created_at, updated_at, created_by, updated_by, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Timezone,
		&i.Locale,
		&i.IsActive,
		&i.LastLoginAt,
		&i.MfaSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT p.key
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleKeys = `-- name: GetUserRoleKeys :many
SELECT r.key
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoleKeys(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoleKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT 
    ag.id,
    ag.user_id,
    ag.display_name,
    ag.signature_html,
    ag.is_available,
    ag.max_concurrent_tickets,
    ag.skills,
    u.email,
    (SELECT count(*) FROM tickets t WHERE t.assigned_agent_id = ag.id AND t.deleted_at IS NULL AND t.status_category IN ('open', 'pending')) AS open_ticket_count
FROM agents ag
JOIN users u ON u.id = ag.user_id
WHERE ag.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY ag.display_name ASC
`

type ListAgentsRow struct {
	ID                   pgtype.UUID `json:"id"`
	UserID               pgtype.UUID `json:"user_id"`
	DisplayName          string      `json:"display_name"`
	SignatureHtml        string      `json:"signature_html"`
	IsAvailable          bool        `json:"is_available"`
	MaxConcurrentTickets int32       `json:"max_concurrent_tickets"`
	Skills               []string    `json:"skills"`
	Email                string      `json:"email"`
	OpenTicketCount      int64       `json:"open_ticket_count"`
}

func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.SignatureHtml,
			&i.IsAvailable,
			&i.MaxConcurrentTickets,
			&i.Skills,
			&i.Email,
			&i.OpenTicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT 
    tm.id,
    tm.name,
    tm.slug,
    tm.lead_agent_id,
    tm.inbox_email,
    tm.assignment_strategy,
    tm.restrict_visibility,
    (SELECT count(*) FROM team_members tmb WHERE tmb.team_id = tm.id AND tmb.deleted_at IS NULL) AS member_count,
    (SELECT count(*) FROM tickets t WHERE t.assigned_team_id = tm.id AND t.deleted_at IS NULL AND t.status_category IN ('open', 'pending')) AS open_ticket_count
FROM teams tm
WHERE tm.deleted_at IS NULL
ORDER BY tm.name ASC
`

type ListTeamsRow struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	Slug               string      `json:"slug"`
	LeadAgentID        pgtype.UUID `json:"lead_agent_id"`
	InboxEmail         pgtype.Text `json:"inbox_email"`
	AssignmentStrategy string      `json:"assignment_strategy"`
	RestrictVisibility bool        `json:"restrict_visibility"`
	MemberCount        int64       `json:"member_count"`
	OpenTicketCount    int64       `json:"open_ticket_count"`
}

func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsRow
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LeadAgentID,
			&i.InboxEmail,
			&i.AssignmentStrategy,
			&i.RestrictVisibility,
			&i.MemberCount,
			&i.OpenTicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
